### ISSUE TITLE
New feature: Changing fees

### ISSUE THREAD

**Issue by bitsol** [breadwallet/breadwallet-android#10]
The only thing this wallet is truly missing is the ability to overwrite the auto-generated fees. By default, obviously, the wallet should use the dynamic fees (to prevent newbies from complaining that their transactions aren't going through).

What are your thoughts?

**Comment by Gutyn** [comment]
BreadWallet was designed to be as simple as possible and the fees are a complex issue even for expert users, so we decided to adjust it dynamically in order to target 2-3 blocks of confirmation time. Let me know if you have additional questions.
