### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by VaivalGithub** [breadwallet/breadwallet-android#100]
ERROR: Unable to resolve dependency for ':app@brdDebug/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdDebugAndroidTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdDebugUnitTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdRelease/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdReleaseUnitTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdTestnetDebug/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdTestnetDebugAndroidTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdTestnetDebugUnitTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdTestnetRelease/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@brdTestnetReleaseUnitTest/compileClasspath': Could not resolve project :CoreLibrary.
Show Details
Affected Modules: app

**Comment by shivangigandhi** [comment]
This is a duplicate of #99. 

Closing.
