### ISSUE TITLE
Add Deployment to F-Droid

### ISSUE THREAD

**Issue by drGrove** [breadwallet/breadwallet-android#102]
F-Droid is the FOSS equivalent of the play store and allows for apps to be used without Google Services.

**Comment by anonymous73** [comment]
Deployment on F-Droid would be great, yes.

Does the app work on Kitkat?

**Comment by shivangigandhi** [comment]
The app was designed for Android 6.0 and above.

Regarding F-Droid, I think I looked into this in the past and we did not meet the requirements.  We can evaluate again.

**Comment by trymeouteh** [comment]
Please remove the Crashlytics and Firebase.

**Comment by DrewCarlson** [comment]
At this time we do not have any plans to remove Google Play Services, Firebase, or Crashlytics.  The buy/sell/trade functionality is provided through a locally stored website that can be updated using a remote server.  Additionally [WalletKit](https://github.com/blockset-corp/walletkit) requires a [Blockset](https://blockset.com) API key that we do not store inside of the release binaries or the public source code.  It is my understanding that for these reasons F-Droid inclusion is not possible.

**Comment by leafcutterant** [comment]
["BRD Is Breaking Into the Crypto Compliance Game" (Coindesk, Sep 22, 2020)](https://www.coindesk.com/brd-is-breaking-into-the-crypto-compliance-game)

To me it looks like BRD could use some face saving in this regard. Removing Google-related tools from the code base and making your app compatible with F-Droid would be a very welcome way to do that.

> Additionally WalletKit requires a Blockset API key that we do not store inside of the release binaries or the public source code.

Does this mean that the public source code is insufficient for producing a working build of BRD?

**Comment by DrewCarlson** [comment]
> Does this mean that the public source code is insufficient for producing a working build of BRD?

No, we continue to maintain the ability for a clone to build and run correctly.  The readme mentions the Google Service keys and the Blockset API key, additionally the font used in the Play Store is not published on Github because of licensing restrictions.  If you find that a clone does not run correctly, please open an issue as others have and we will do our best to resolve it.

**Comment by alefvanoon** [comment]
i think still you can add it to IzzyOnDroid repo with google service.

**Comment by alefvanoon** [comment]
so it's now available from my repo.(not main F-droid repo)
just need to add this repo: https://repo.alefvanoon.xyz/fdroid/repo/?fingerprint=04DF198F553069C7BE60F057AE12000E99F7700DA895CC1CE2EB11DC871581F1
and download breadwallet...
 
![image](https://user-images.githubusercontent.com/53198048/120894460-4dd98280-c5cd-11eb-8989-9076146f336a.png)

**Comment by leafcutterant** [comment]
@alefvanoon I really appreciate your effort and this is a great start towards making the app available outside the app stores! At the same time, I need to point out that it is the authors of the software that need to either release an F-Droid repo or submit the app to the official one. Having someone else maintain that repo is an another potential point of failure that users can't be expected to trust, especially for a financial app.

With that I'd like to urge @shivangigandhi to re-open this issue and consider at least creating a custom F-Droid repository as @alefvanoon did.
