### ISSUE TITLE
Error:CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by mmmce1994** [breadwallet/breadwallet-android#11]
hi everyone!
after clone project in android studio and when the gradle is working, we faced with this error :  
Error:CreateProcess error=2, The system cannot find the file specified  
any idea ??

**Comment by mrkwenzel** [comment]
This issue helped me: https://github.com/ajoberstar/gradle-git/issues/134

Summary: You have to add the bin folder, of your git installation, to your path environment variable.

**Comment by mmmce1994** [comment]
it worked! tnx
