### ISSUE TITLE
secp256k1/src/basic-config.h not found

### ISSUE THREAD

**Issue by mutablestudio** [breadwallet/breadwallet-android#115]
Android Studio 3.5.1 w clean checkout of breadwallet-android. after rebuilding or doing gradle sync -> build, getting an error from BRKey.c looking for a non existent secp256k1 file.

`../breadwallet-android/core/support/BRKey.c:55:10: fatal error: 'secp256k1/src/basic-config.h' file not found (core/support/BRKey.c line 55)`

after `git submodule init` and `git submodule update --recursive`, the core directory contains a `secp256k1` directory but it's empty.

**Comment by DrewCarlson** [comment]
The setup instructions are incorrect.  The first command will not initialize core's submodules so the second command will not clone `secp256k1`.  This repository needs to be cloned with `--recurse-submodules` or since you've already cloned: `git submodule update --init --recursive`.

**Comment by mutablestudio** [comment]
@DrewCarlson works, thx!
