### ISSUE TITLE
Improve verifiability

### ISSUE THREAD

**Issue by Giszmo** [breadwallet/breadwallet-android#117]
At the time I did try to verify the wallet for [this article](https://walletscrutiny.com/posts/2019/11/brd/), the released app was ahead(?) of the published code. Looking forward to seeing better verifiability soon.

**Comment by DrewCarlson** [comment]
Thanks for reporting this.  The source code for the version you tested and the current Google Play release (3.14.3) is already available on master though I have just pushed the missing tags for [3.14.2](https://github.com/breadwallet/breadwallet-android/releases/tag/build-3.14.2.1) and [3.14.3](https://github.com/breadwallet/breadwallet-android/releases/tag/build-3.14.3.3).

**Comment by Giszmo** [comment]
Noted. I will re-evaluate shortly. Feel free to ping me if in 2 days there is no update here or on my site.

**Comment by Giszmo** [comment]
So I tried again and it did not look much better. Hope my findings are helpful. I guess build instructions should use docker to get rid of the diff that will remain from the username "ajv" compiled into the apk.

**Comment by Giszmo** [comment]
3.5 months later guys. Any chance you fix this soon?

**Comment by vevek** [comment]
Any updates?

**Comment by DrewCarlson** [comment]
Some work has been done and we are actively evaluating the remaining tasks.  I should have a meaningful update here soon.

Thanks for your patience.

**Comment by Giszmo** [comment]
I'm patient :D GitHub is great at informing me when there is progress on any of the 25 issues in 25 wallets.

I am though thinking about rewording "not verifiable" on walletscrutiny to something more negative. "Partly closed source" maybe, as only reproducibility could proof that the code was published.

For now, I only changed the color of the "not verifiable" classification from the neutral black to a more alarming red.

You let me know when you think it is reproducible. If you have difficulties in that regard, please point me to issues. Maybe I can help.

**Comment by prefix309** [comment]
Any updates guys?
I want to see you on the Reproducible list soon.

**Comment by Giszmo** [comment]
@DrewCarlson I see your [inactive merge request](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/merge_requests/56) ... Can I help you with anything?

**Comment by DrewCarlson** [comment]
At this time we are unable to provide adequate steps for verifying a Play Store release against a local build.

The obvious issues present are the use of private `google-services` and `mobile-font` submodules containing the google-services.json and font files used in production.  Without being able to checkout submodules sensible default behavior is applied to allow a local build to succeed and run.  A public clone and build would have at least these differences making verification difficult.

Additionally the current procedure for creating production APKs occurs on a MacBook using Android Studio’s build and sign functions.  In my testing two MacOS environments using the same AS and build tool versions produce numerous (though minor) differences in byte code when built via the IDE.  Ignoring that problem the ideal solution would to build inside a docker container available to everyone, but this is not considered a secure option and production build procedures are unlikely to change.

**Comment by Giszmo** [comment]
The api keys in public source repositories is a perceived issue but upon closer inspection it should be clear that those api keys cannot be kept secret. I could trivially find them from your apk with apktools and grep. And [this search](https://github.com/search?q=%2B%22mobilesdk_app_id%22&type=Code) suggests that thousands of projects share those api keys. Of course, the wallet should not allow abuse such as trusting a firebase message about an incoming payment for example if those keys could be abused for that which I am not convinced they could. `mobile-font`sounds like less of an issue.

Android Studio uses gradle internally and you can also see the gradle commands it uses to get to its results. Building with AS should thus not differ from building on the cli. Non-determinism most commonly results from non-deterministic build tools and some of those can be tackled by using disorderfs or otherwise using a file system that reads files not in chronological order but in alphabetic order.

In the end, only reproducible builds can protect the company from rogue release managers or hackers that manage to get into his machine or criminals that take his family hostage, so if the private repositories have to remain private to the company at all cost, please consider fixing the other issues at least internally, so that the release manager can follow the kidnappers' demands with peace of mind that his colleagues will catch the backdoor before it is being shipped to in your case about one million users with their probably hundreds of millions of $$. If you don't proof it to all the world, please at least internally make sure BRD will not be MtGox 2.0. ;)

**Comment by DrewCarlson** [comment]
Forgot to close this with my last comment but will do so now as we are not actively working on this, feel free to continue discussing or open new issues as needed.

For clarity on the Google Services API keys, we do not consider these secrets and the original keys remain available in the commit history.  This was done to allow clones/forks to build without using Google Services and prevent these projects from intruding data into our crash reporting console.

**Comment by BlockchainVRCloudAI** [comment]
I guess reproducibility is a big ask if you haven't even published code for the versions released in production for more than three months (https://github.com/breadwallet/breadwallet-android/issues/196). At this point the application is not even open source.

**Comment by Giszmo** [comment]
@BlockchainVRCloudAI thanks for headsup! That's indeed sad to see :(

**Comment by DrewCarlson** [comment]
The latest releases are available here https://github.com/breadwallet/brd-mobile
