### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zhupengxiang** [breadwallet/breadwallet-android#124]
How to solve it?
![image](https://user-images.githubusercontent.com/17894209/77039151-50fc4900-69f0-11ea-9ed7-aa430978adef.png)

**Comment by DrewCarlson** [comment]
Thanks for the report.

We are missing Windows dependency checksum for Gradle verification.

For now you can run `./gradlew --write-verification-metadata sha256` to add the missing information or follow the [Gradle documentation](https://docs.gradle.org/6.2.2/userguide/dependency_verification.html#sec:disabling-metadata-verification) to disable verification in [`gradle/verification-metadata.xml`](gradle/verification-metadata.xml).

**Comment by zhupengxiang** [comment]
Thanks! 😄
