### ISSUE TITLE
Implement fee schedule selection for transactions on Ethereum

### ISSUE THREAD

**Issue by leafcutterant** [breadwallet/breadwallet-android#128]
This is a feature request to let the user choose the transaction "processing speed" (fee level, really) for ETH and Ethereum-based token transactions, as already implemented for BTC.

Thank you so much for this unique wallet!

**Comment by DrewCarlson** [comment]
Thank you for the request, this is on our roadmap for a future version.

**Comment by DrewCarlson** [comment]
In [4.4.4](https://github.com/breadwallet/breadwallet-android/releases/tag/build-4.4.4.13), the fee selector was added for ETH and ERC20 transfers in the same way as Bitcoin.

**Comment by leafcutterant** [comment]
Wonderful, thank you a lot! May I ask what service you use for gas price estimations?

**Comment by DrewCarlson** [comment]
[ethgasstation.info](https://ethgasstation.info)
