### ISSUE TITLE
Option to speed up Ethereum transactions (both ETH and ERC20 tokens)

### ISSUE THREAD

**Issue by leafcutterant** [breadwallet/breadwallet-android#133]
Please offer a way to speed up ETH and ERC20 token transactions that have not yet been included in a block.

This would involve sending the transaction with the same nonce but a higher gas price (see MetaMask).

Multiple speed-up levels (e.g. three, like with the BTC transactions) would be also very much welcome.

**Comment by DrewCarlson** [comment]
Thanks for the request, this is on our roadmap.

**Comment by DrewCarlson** [comment]
In [4.4.4](https://github.com/breadwallet/breadwallet-android/releases/tag/build-4.4.4.13), the fee selector was added for ETH and ERC20 transfers in the same way as Bitcoin.
