### ISSUE TITLE
Getting error while building the project 

### ISSUE THREAD

**Issue by emtalent9** [breadwallet/breadwallet-android#148]
A problem occurred configuring root project 'breadwallet-android-master'.
> Dependency verification failed for configuration ':classpath'
 4 artifacts failed verification:
    - transform-api-2.0.0-deprecated-use-gradle-api.pom (com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api) from repository Google
    - bundletool-0.10.3.pom (com.android.tools.build:bundletool:0.10.3) from repository Google
    - jetifier-core-1.0.0-beta08.pom (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta08) from repository Google
    - jetifier-processor-1.0.0-beta08.pom (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta08) from repository Google
  This can indicate that a dependency has been compromised. Please carefully verify the checksums.

**Comment by DrewCarlson** [comment]
This happens from time to time, usually when using Android Studio.

Some things to try:
- Reinstall Android Studio 3.6
- Update all Android Studio components
- Delete `~/.gradle`

If none of that works, dependency verification can be disabled by setting these flags to `false`:
https://github.com/breadwallet/breadwallet-android/blob/130445221337a8fecd456408a1bf548e46bce99a/gradle/verification-metadata.xml#L4-L5

**Comment by emtalent9** [comment]
@DrewCarlson Thanks
I have set this 

<verify-metadata>false</verify-metadata>
<verify-signatures>true</verify-signatures>

then it successfully builds

**Comment by DrewCarlson** [comment]
Great!

That works because the items failing to validate are pom files (i.e. metadata).  Dependency verification is still active for jar files.
