### ISSUE TITLE
Reasons behind the `Error: Could not publish transaction.`

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#151]
Hi, sometimes I am getting the following error sending BTC to another wallet:

![Screen Shot 2020-07-13 at 12 30 04 PM](https://user-images.githubusercontent.com/142539/87329353-cee6e180-c504-11ea-9654-e1576d96249e.png)

Could you help me understand what are the possible reasons for this error?
When I get this error if I keep retrying it is will keep failing, the only work around is to restart the app.

**Comment by DrewCarlson** [comment]
This is the default message if an error reason cannot be determined though in your case it's likely due to a bug.  If you're still having frequent send issues in 4.4.1, please let us know.

**Comment by dabitdev** [comment]
Hi @DrewCarlson I am maintaining a fork (forked on 4.4.1), looks like the app can go to a state where keeps failing.
At what layer is this error coming? (from core)? It be possible that the wallet has to be fully sync.

On the other hand, could I check a changelog or a more specific readme file to see all the changes / bugfixies to see how critical is to posponed a rebase to my fork.

Thank you

**Comment by DrewCarlson** [comment]
We do not currently maintain a change log outside of the Play Store.  That message is typically a result of calling a Core API but in this case it may be an issue in application code.  If your wallet is in P2P mode (the fastsync setting is off), you'll need to wait until the sync is complete or this error is guaranteed.

**Comment by dabitdev** [comment]
PlayStore change log is not very useful for developers.
Thank you, for you fast response.

Best,
David
