### ISSUE TITLE
Upgrade fastadapter dependency from 4.1.2 to 5.2.2

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#154]
@DrewCarlson could I create pull request?

Best,
David

**Comment by DrewCarlson** [comment]
Absolutely! 🙂

**Comment by dabitdev** [comment]
I updated `fastadapter_version` from 4.1.2 to 5.2.2
I updated `gradle plugin` to 4.0.0 to 4.0.1

BTW the NDK got a new version 21.3.6528147 (existing 21.0.6113669)

**Comment by DrewCarlson** [comment]
Merged as https://github.com/breadwallet/breadwallet-android/commit/f61571b8108862d231fcdc915dcd8fec189ec703
