### ISSUE TITLE
why ios is using data.fixer.io and andorid uses only coingecko?

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#165]
it looks like ios is calling fixer.io to fetch currencies while andorid uses only coingecko. 
Could you explain me why?

I found and API in ios client
http://data.fixer.io/api/latest?access_key=asdfasdf&base=USD&symbols=BTC

Thank you!

**Comment by DrewCarlson** [comment]
Some cryptocurrency market pairs have insufficient data or in some cases, no data at all.  Fixer is a fiat rate data provider that allows us to use pairs like USD/BTC or EUR/BTC and then convert the fiat to the user's preferred currency, like DKK or HRK.  This will provide much more accurate rate information for users of certain fiat currencies though it's not yet fully implemented on either platform.
