### ISSUE TITLE
Mobius framework : Code conversion (Help wanted)

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#167]
Is there any way that we can convert the code into mobius architecture or just do it by manually?
Thanks!

**Comment by DrewCarlson** [comment]
Could you describe your goal in more detail?  Are you looking to convert some legacy code that exists in this repo or add new feature?

Either way I'd suggest reviewing the Mobius workflow and related docs [here](https://github.com/spotify/mobius/wiki/The-Mobius-Workflow).  We use a [coroutines adapter](https://github.com/DrewCarlson/mobius-coroutines/) which has a similar API to the official RxJava adapters. A good example of how we use Mobius is the [Sync Blockchain](https://github.com/breadwallet/breadwallet-android/tree/master/app/src/main/java/com/breadwallet/ui/sync) screen.

**Comment by expertdev-designer** [comment]
Thanks for reply.
Actually i am new with Blockchain also Mobius framework is new for me .I want to review the code but i don't understand it yet properly.I will go through the doc hope it's helpful for me.
