### ISSUE TITLE
Internet check issue

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#168]
On HomeController

ifChanged(M::hasInternet) {

            notification_bar.apply {
                isGone = hasInternet
                if (hasInternet) bringToFront()
            }
        }
this check always return "true" value(have/have not internet).Why?

**Comment by DrewCarlson** [comment]
Thanks for the report.  It always returns true because the source of the network state is not wired up anymore.  We will restore this functionality in an upcoming release.

**Comment by ahsanb786** [comment]
This issue has been fixed. Thank you once again for the report.

**Comment by expertdev-designer** [comment]
@ahsanb786 Glad to help:)
