### ISSUE TITLE
Add (optional) BIP148 mode

### ISSUE THREAD

**Issue by kek-coin** [breadwallet/breadwallet-android#17]
It should be possible to enforce BIP148 even with SPV wallets, as BIP148 only enforces versionbit signalling and therefore should be viable in header-chain mode.

**Comment by kek-coin** [comment]
My bad for opening it in two places, opened this one first before someone pointed out I should open [an issue on the iOS repo](https://github.com/voisine/breadwallet/issues/425) as well since it is the bigger project. For future reference; any non-android-specific issues should be opened on the iOS repo?

**Comment by Gutyn** [comment]
Hi, @kek-coin, pretty much all the wallet-specific issues or comments (such as fee calculations, BIP questions and so on) should go to the ios repo, all the Android-specific issues (Android code, security etc) - here. Thanks.
