### ISSUE TITLE
Something went wrong (Help wanted)

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#170]
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build/bundletool/0.13.2/9dab70a6f932d0afe88f857eb168c3ad8ba9f3fe/bundletool-0.13.2.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build/bundletool/0.13.2/9dab70a6f932d0afe88f857eb168c3ad8ba9f3fe/bundletool-0.13.2.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build.jetifier/jetifier-core/1.0.0-beta09/6393d821ad5c2917a0182717ae8b8eee72c667de/jetifier-core-1.0.0-beta09.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build.jetifier/jetifier-core/1.0.0-beta09/6393d821ad5c2917a0182717ae8b8eee72c667de/jetifier-core-1.0.0-beta09.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build.jetifier/jetifier-processor/1.0.0-beta09/c5b7c0ddbdfdeb69b842bcd9672f88bae14238c7/jetifier-processor-1.0.0-beta09.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
Cannot compute checksum for /Users/admin/.gradle/caches/modules-2/files-2.1/com.android.tools.build.jetifier/jetifier-processor/1.0.0-beta09/c5b7c0ddbdfdeb69b842bcd9672f88bae14238c7/jetifier-processor-1.0.0-beta09.pom because it doesn't exist. It may indicate a corrupt or tampered cache.
A verification file was generated but some problems were discovered:
   - some artifacts aren't signed or the signature couldn't be retrieved.
   - some signature verification failed. Checksums were generated for those artifacts but you MUST check if there's an actual problem. Look for entries with the following comment: PGP verification failed
![Screen Shot 2020-09-28 at 11 42 41 AM](https://user-images.githubusercontent.com/52417551/94398628-85ad4200-0183-11eb-9511-c622de314249.png)

**Comment by expertdev-designer** [comment]
@DrewCarlson Please look into this

Dependency verification failed for configuration ':classpath'
3 artifacts failed verification:
  - bundletool-0.13.2.pom (com.android.tools.build:bundletool:0.13.2) from repository Google
  - jetifier-core-1.0.0-beta09.pom (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta09) from repository Google
  - jetifier-processor-1.0.0-beta09.pom (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta09) from repository Google
This can indicate that a dependency has been compromised. Please carefully verify the checksums.

Open this report for more details: file:///Users/admin/Desktop/AndroidProjects/BreadWallet22Commit/BreadWalletLatest/build/reports/dependency-verification/at-1601281156076/dependency-verification-report.html

**Comment by DrewCarlson** [comment]
This is an issue with Gradle/AGP, the easiest way to fix it is by deleting your `~/.gradle` folder and running it again.

**Comment by expertdev-designer** [comment]
@DrewCarlson Thanks!
It's working fine now.
