### ISSUE TITLE
What features do they use the local HTTPServer?

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#171]
Hi, I would like to know what features are using the local HTTPServer. I am considering removing the local server in my fork.
From what I saw the local server is used in the following features:
- SupportPages
- Buy
- Trade
- BRD Rewards

Am I missing something?

Best,
David

**Comment by DrewCarlson** [comment]
I think that's all the features.  Removing WebController, HTTPServer and dependents should get rid of everything.

We have started on a long-term goal of replacing the web server with native javascript interfaces.  These are only used by WebController and found in [`com.platform.jsbridge`](https://github.com/breadwallet/breadwallet-android/tree/4cc3727bb8dd9e0cdd65472c798466718f7d9711/app/src/main/java/com/platform/jsbridge).

**Comment by dabitdev** [comment]
Thank's for your response and for exposing the long-term goal.
