### ISSUE TITLE
Getting Issue with dependancy verification

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#174]
Dependency verification failed for configuration ':app:classpath'
23 artifacts failed verification:
  - commons-codec-1.9.pom (commons-codec:commons-codec:1.9) from repository Gradle Central Plugin Repository
  - commons-parent-32.pom (org.apache.commons:commons-parent:32) from repository Gradle Central Plugin Repository
  - detekt-gradle-plugin-1.0.1.pom (io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.1) from repository Gradle Central Plugin Repository
  - gradle-download-task-3.4.3.pom (de.undercouch:gradle-download-task:3.4.3) from repository Gradle Central Plugin Repository
  - httpclient-4.5.3.pom (org.apache.httpcomponents:httpclient:4.5.3) from repository Gradle Central Plugin Repository
  - httpcomponents-client-4.5.3.pom (org.apache.httpcomponents:httpcomponents-client:4.5.3) from repository Gradle Central Plugin Repository
  - httpcomponents-core-4.4.6.pom (org.apache.httpcomponents:httpcomponents-core:4.4.6) from repository Gradle Central Plugin Repository
  - httpcore-4.4.6.pom (org.apache.httpcomponents:httpcore:4.4.6) from repository Gradle Central Plugin Repository
  - io.gitlab.arturbosch.detekt.gradle.plugin-1.0.1.pom (io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.0.1) from repository Gradle Central Plugin Repository
  - kotlin-android-extensions-1.3.41.pom (org.jetbrains.kotlin:kotlin-android-extensions:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-annotation-processing-gradle-1.3.41.pom (org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-build-common-1.3.41.pom (org.jetbrains.kotlin:kotlin-build-common:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-compiler-runner-1.3.41.pom (org.jetbrains.kotlin:kotlin-compiler-runner:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-daemon-client-1.3.41.pom (org.jetbrains.kotlin:kotlin-daemon-client:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-gradle-plugin-1.3.41.pom (org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-gradle-plugin-api-1.3.41.pom (org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-gradle-plugin-model-1.3.41.pom (org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-scripting-common-1.3.41.pom (org.jetbrains.kotlin:kotlin-scripting-common:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-scripting-compiler-embeddable-1.3.41.pom (org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-scripting-compiler-impl-embeddable-1.3.41.pom (org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.3.41) from repository Gradle Central Plugin Repository
  - kotlin-scripting-jvm-1.3.41.pom (org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.41) from repository Gradle Central Plugin Repository
  - kotlinx-coroutines-core-1.1.1.pom (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1) from repository Gradle Central Plugin Repository
  - project-7.pom (org.apache.httpcomponents:project:7) from repository Gradle Central Plugin Repository
This can indicate that a dependency has been compromised. Please carefully verify the checksums.

Open this report for more details: file:///Users/admin/Desktop/AndroidProjects/BlockCard_android_latest_12oct/build/reports/dependency-verification/at-1602826227955/dependency-verification-report.html

**trying things**
- delete gradle >Rebuild 
- ./gradlew --write-verification-metadata sha256,pgp --export-keys run it on terminal after that rebuild then run
- clean project then rebuild
- invalidate cache and restart

not single thing works for me.Help wanted
Thanks!

**Comment by expertdev-designer** [comment]
@DrewCarlson Now, i have set 
**<verify-metadata>false</verify-metadata>
<verify-signatures>true</verify-signatures>**
metadata -false then it's working fine.But i want to know why this happened most of time .
Am i doing something wrong?

**Comment by DrewCarlson** [comment]
The cause is unclear from the information provided, but disabling metadata verification is a fine solution if you're just exploring the project and making personal changes.

If you share the `dependency-verification-report.html` file I may be able to identify the issue.  It appears that IDE configuration may be problem so if you want to enable metadata again, run `./gradlew --stop` and then `./gradlew --write-verification-metadata pgp,sha256 --export-keys` from the terminal outside of your IDE.
