### ISSUE TITLE
Any way to show/filter some token : Help

### ISSUE THREAD

**Issue by expertdev-designer** [breadwallet/breadwallet-android#175]
Hiii @DrewCarlson 
Is there any way that i can show/filter out some tokens?

**Tried out :**
I have commented some tokens from `tokens.json` file but yet these are showing in app.
Thanks.

**Comment by DrewCarlson** [comment]
The embedded `tokens.json` file is used for the first run and updated using the BRD API. The remote update can be disabled by removing this line: https://github.com/breadwallet/breadwallet-android/blob/3de7a22e4c3c5dac6847080a4697431bd64d58f2/app/src/main/java/com/breadwallet/tools/util/TokenUtil.kt#L110

**Comment by expertdev-designer** [comment]
Thanks for Reply @DrewCarlson 
How i can hide the` BRD Token` from Home?

**Comment by DrewCarlson** [comment]
Remove it from the default wallets list.  https://github.com/breadwallet/breadwallet-android/blob/8b7ce471ae70cb294c512c8d4f8e440700a24cfb/app/src/main/java/com/breadwallet/app/BreadApp.kt#L164-L175

**Comment by expertdev-designer** [comment]
Thanks:)
