### ISSUE TITLE
Can't find the image resource of the token?

### ISSUE THREAD

**Issue by MarkTangJs** [breadwallet/breadwallet-android#177]
I want to add my own token to the current token list, but I can’t find the image resource of the existing token. Where? Is it not placed locally? How can I get them?

please help

**Comment by dabitdev** [comment]
did you try checking inside of the bundles (tar files)?

**Comment by DrewCarlson** [comment]
You'll find the token icons in the [`brd_tokens.tar`](https://github.com/breadwallet/breadwallet-android/blob/master/app/src/main/res/raw/brd_tokens.tar) bundle.
