### ISSUE TITLE
[Educational] how the wallet manages the network fees?

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#178]
hi,

I would like to have more visibility about what classes/files are involved in the calculation of the network fee and if there is server api involved in the process of exposing to the user the Economy, Regular and Priority. Finally, how it is everything working when there is a high congestion on the BTC network.

Best,
David

**Comment by DrewCarlson** [comment]
Fee data is provided by Blockset and maintained by WalletKit at runtime.  Application code uses a duration for each fee tier (e.g. Economy=7h or Priority=1m) and attempts to find the value which will allow the transaction to completed in that time.  Times for the fee tiers are in the [TransferSpeed](https://github.com/breadwallet/breadwallet-android/blob/3de7a22e4c3c5dac6847080a4697431bd64d58f2/app/src/main/java/com/breadwallet/breadbox/TransferSpeed.kt#L37).  You can see the realtime fee values from blockset Blockset [here](https://docs.blockset.com/sandbox?endpoint=blockchains%2Fbitcoin-mainnet&verb=get&body=body%3Dmybody).

**Comment by dabitdev** [comment]
Thank you DrewCarlson! you are always helpful.
