### ISSUE TITLE
relayed orphan block !!!

### ISSUE THREAD

**Issue by mmmce1994** [breadwallet/breadwallet-android#18]
we implement our network and genesis block as a test network and apply our changes to breadwallet-core
it woke for 2 days and breadwallet has been synced without any problem
today when app was syncing , we faced with "relayed orphan block !!!" error and not synced to network
any idea ?

**Comment by SPRING-Z** [comment]
so am I.

the log:

07-07 16:06:39.793 26539-26739/com.breadwallet I/bread: 43.225.47.154:6803 relayed orphan block 02231cf66dbe71b2e1c23b19109e3d5e0b83721b76c39de7def3f9a9ca4d029f, previous 2f4c131a47aca53683f9dfbbc6e8edaa029adff745bb5490fb9943722f6b1865, last block is 692c113d4a3f65c78975ea22651555ec9f08f957a5e8e347041073f65b190000, height 0
07-07 16:06:43.791 26539-26739/com.breadwallet I/bread: 43.225.47.154:6803 Connection timed out
07-07 16:06:43.791 26539-26739/com.breadwallet I/bread: 43.225.47.154:6803 disconnected
07-07 16:06:43.805 26539-26739/com.breadwallet D/Message from C:: networkIsReachable
07-07 16:06:43.805 26539-26739/com.breadwallet D/Message from C:: getEnv peerManager
07-07 16:06:43.806 26539-26739/com.breadwallet D/com.breadwallet.wallet.BRPeerManager: networkIsReachable
07-07 16:06:43.809 26539-26739/com.breadwallet I/bread: 43.225.47.154:6803 connecting
07-07 16:06:43.810 26539-26739/com.breadwallet D/Message from C:: txStatusUpdate
07-07 16:06:43.810 26539-26739/com.breadwallet D/Message from C:: getEnv peerManager
07-07 16:06:43.810 26539-26739/com.breadwallet D/com.breadwallet.wallet.BRPeerManager: txStatusUpdate
07-07 16:06:43.812 26539-27097/com.breadwallet D/Message from C:: getTransactions
07-07 16:06:43.878 26539-27096/com.breadwallet I/bread: 43.225.47.154:6803 socket connected
07-07 16:06:43.879 26539-27096/com.breadwallet I/bread: 43.225.47.154:6803 sending version
07-07 16:06:43.941 26539-27096/com.breadwallet I/bread: 43.225.47.154:6803 Connection reset by peer
07-07 16:06:43.941 26539-27096/com.breadwallet I/bread: 43.225.47.154:6803 disconnected
07-07 16:06:43.953 26539-27096/com.breadwallet D/Message from C:: networkIsReachable
07-07 16:06:43.953 26539-27096/com.breadwallet D/Message from C:: getEnv peerManager
07-07 16:06:43.954 26539-27096/com.breadwallet D/com.breadwallet.wallet.BRPeerManager: networkIsReachable

**Comment by Gutyn** [comment]
@mmmce1994 just make sure your changes to the difficulty algorithm are correct. This seems to be a possible cause.
