### ISSUE TITLE
Build fails!

### ISSUE THREAD

**Issue by herou** [breadwallet/breadwallet-android#180]
Pulled the repo and tried to build it but I am facing this issue: 

![image](https://user-images.githubusercontent.com/13895430/99316026-e68ff700-2863-11eb-9c20-e8f010fd34a0.png)

Any Idea?

**Comment by herou** [comment]
FYI: deleting the breadwallet-android/gradle/verification-metadata.xml file and syncing the project from the beginning worked!

Suggestions: Please, open a ticket for this issue so next time, if somebody pulls the repo, would not face this issue or include it as a step which has to be done in the initial documentation.

Idea: I can work on this ticket if you wish :)

**Comment by DrewCarlson** [comment]
Thanks for the report.  This is a bug in Android's tooling, we have disabled dependency verification in an upcoming release.

**Comment by herou** [comment]
@DrewCarlson No problem, it is a pleasure.

**Comment by herou** [comment]
@DrewCarlson  Do you welcome people to contribute?

**Comment by DrewCarlson** [comment]
Yes, contributions are welcome.  We don't have public documentation or a list of tasks yet, we'll discuss this internally soon.  There are open issues or todos in the code that can be addressed, but most would not be good first issues.

**Comment by herou** [comment]
> Yes, contributions are welcome. We don't have public documentation or a list of tasks yet, we'll discuss this internally soon. There are open issues or todos in the code that can be addressed, but most would not be good first issues.

So, Do not you have nothing for now?

**Comment by DrewCarlson** [comment]
Dependency verification is disabled in https://github.com/breadwallet/breadwallet-android/commit/71e73fc6f6aeff3cda18eb0c4241e694c601270b
