### ISSUE TITLE
add to F-droid main repo

### ISSUE THREAD

**Issue by alefvanoon** [breadwallet/breadwallet-android#194]
pleas add brd wallet to F-droid.
I think it was easier to trust!

**Comment by shivangigandhi** [comment]
@alefvanoon 

Thanks for the feedback.  

We would love to add the wallet to F-droid and have evaluated doing so several times over the years. See [here](https://github.com/breadwallet/breadwallet-android/issues/102#issuecomment-699091147). Also you'll notice many other discussions on the topic if you search our issue list for "f-droid".  If any thing changes in the future, we'll let you know.

I will close this issue for now.  Thanks!
