### ISSUE TITLE
Missing code for version 4.10.0 on google-play

### ISSUE THREAD

**Issue by emanuelb** [breadwallet/breadwallet-android#196]
The version in google-play is: 4.10.0 Updated: April 22, 2021
https://play.google.com/store/apps/details?id=com.breadwallet

While the latest version found in this repo is 4.9.1.1:
https://github.com/breadwallet/breadwallet-android/blob/39f16c570e3f5afc3678572e9a1d5854ffccb43b/buildSrc/src/main/kotlin/brd/BrdRelease.kt
and latest commit from: Mar 10, 2021:
https://github.com/breadwallet/breadwallet-android/commit/a6b8add794ced98b2ea77c3dcecaadd7a91dfdd7

Please publish the code for latest 4.10.0 version on google-play, and in future ensure that code is published before it's released to google-play.

**Comment by shivangigandhi** [comment]
Hi @emanuelb! 

Thanks for your feedback! We really appreciate it. 

Sorry that we taken a while to update our public repo to 4.10.0.  We've made some exciting changes to the codebase and we want to be extra careful to make sure the transition to 4.10.0 goes smoothly for our community.  We're working on resolving the last few issues and should be able to update the code by the end of the month.

Thanks for your continued interest and support in our project!

**Comment by DrewCarlson** [comment]
The latest Android and iOS releases can be found at https://github.com/breadwallet/brd-mobile
