### ISSUE TITLE
 Could not resolve dev.zacsweers.redacted:redacted-compiler-gradle-plugin

### ISSUE THREAD

**Issue by CyrusCeasar** [breadwallet/breadwallet-android#197]
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://dl.bintray.com/drewcarlson/redacted-plugin/dev/zacsweers/redacted/redacted-compiler-gradle-plugin/0.8.0/redacted-compiler-gradle-plugin-0.8.0.pom'. Received status code 403 from server: Forbidden

Any ideas for this problem?

**Comment by sheindel** [comment]
I'm experiencing the same issue, same issue when I try to retrieve that pom file directly. After finding a totally unrelated issue with a linux package from bintray someone mentioned a planned brownout/maintenance and the status page seems to confirm that this is the situation right now https://bintray.statuspage.io/

**Comment by sheindel** [comment]
Well, the status page shows everything is good now but I get the same error (403) on that file :-(

**Comment by sheindel** [comment]
Hmmm.... maybe this is a consequence of the bintray sunset https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by DrewCarlson** [comment]
That's correct @sheindel.  Two of the repositories that 4.9.1 requires are no longer available.  Both have been removed in 4.10.0 which we will be publishing soon.

**Comment by sheindel** [comment]
@DrewCarlson for the redacted plugin, I was able to redirect to the Apache Maven Central repo

```
diff --git a/build.gradle.kts b/build.gradle.kts
index c76a7a07b..0b0dfa1c9 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -4,7 +4,7 @@ buildscript {
         mavenCentral()
         google()
         jcenter()
-        maven(url = "https://dl.bintray.com/drewcarlson/redacted-plugin") {
+        maven(url = "https://repo.maven.apache.org/maven2") {
             content {
                 includeGroup("dev.zacsweers.redacted")
             }
@@ -34,7 +34,7 @@ allprojects {
         mavenCentral()
         google()
         jcenter()
-        maven(url = "https://dl.bintray.com/drewcarlson/redacted-plugin") {
+        maven(url = "https://repo.maven.apache.org/maven2") {
             content {
                 includeGroup("dev.zacsweers.redacted")
             }
diff --git a/buildSrc/src/main/kotlin/brd/Libs.kt b/buildSrc/src/main/kotlin/brd/Libs.kt
index 9e76e8e33..51338d131 100644
--- a/buildSrc/src/main/kotlin/brd/Libs.kt
+++ b/buildSrc/src/main/kotlin/brd/Libs.kt
@@ -230,7 +230,7 @@ object Libs {
 
     object Redacted {
         const val Annotation = "dev.zacsweers.redacted:redacted-compiler-plugin-annotations:$REDACTED_VERSION"
-        const val Plugin = "dev.zacsweers.redacted:redacted-compiler-gradle-plugin:$REDACTED_VERSION"
+        const val Plugin = "dev.zacsweers.redacted:redacted-compiler-plugin-gradle:$REDACTED_VERSION"
     }
 
     object Detekt {
~
```

**Comment by dabitdev** [comment]
hi @sheindel, I am still gettings this error when I apply your changes:

 java.lang.AssertionError: dev.zacsweers.redacted.compiler.RedactedSyntheticResolveExtension caused LinkageError

more details on https://scans.gradle.com/s/o4ikhxxnyxlpe

**Comment by sheindel** [comment]
@dabitdev unfortunately, this was just a short test for me and I haven't looked at it again. While it got past the initial compilation error, there may be a compatibility issue with the package I found. I will post my results if I ever get back to this. My apologies.

**Comment by DrewCarlson** [comment]
Try compiling with redacted 0.6.1 and make sure you're using Kotlin 1.4.10-1.4.32

**Comment by dabitdev** [comment]
for some reason I am only able to pull the 0.8.0 version, I checked maven and I saw other versions available

https://search.maven.org/artifact/dev.zacsweers.redacted/redacted-compiler-plugin/0.6.1/jar

**Comment by dabitdev** [comment]
I found the issue it was not exactly there are two artifacts: `redacted-compiler-plugin` and `redacted-compiler-plugin-gradle`, the second one has only the version 8.0.0
https://search.maven.org/artifact/dev.zacsweers.redacted/redacted-compiler-plugin-gradle

**Comment by DrewCarlson** [comment]
See https://github.com/DrewCarlson/breadwallet-android/commit/3fba709114784e620d98301069b75eee9ae2d398 for how to compile 4.9.1

**Comment by DrewCarlson** [comment]
Resolved with the latest release, see https://github.com/breadwallet/brd-mobile
