### ISSUE TITLE
BRD Android closes when Re-stake option is selected in Tezos wallet

### ISSUE THREAD

**Issue by leandrodelteso** [breadwallet/breadwallet-android#198]
Hi BRD team,
not sure how to file a bug but I guess you can advise if any information is missing.

Since the last update whenever I click on the Re-stake option in BRD Android the app closes unexpectedly:

![photo_2021-06-11_16-16-06](https://user-images.githubusercontent.com/10621502/121738631-d9bd4400-cad0-11eb-9ad9-63f4da035953.jpg)

BRD Version 4.11.0 Build 8
Android 11
Samsung Galaxy A51

Cheers,
Leandro

**Comment by DrewCarlson** [comment]
Thank you for the report.  We're aware of this issue and have since halted the release of 4.11.0.8.  Soon 4.11.0.9 will be released which fixes this.

In the short term: ensure you've written down your recovery phrase, uninstall the current version, in Google Play reinstall BRD and you'll get 4.10.

**Comment by DrewCarlson** [comment]
This crash is resolved in the latest release.
