### ISSUE TITLE
walletkit-java not found on bintray

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#199]
Could not GET 'https://dl.bintray.com/brd/walletkit-java/com/breadwallet/core/corecrypto-android/6.2.2/corecrypto-android-6.2.2.aar'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

**Comment by dabitdev** [comment]
Hi @DrewCarlson, this is blocking me. Could you upload the artifacts to another maven?
If you could share the artifacts I could add them locally too.

**Comment by DrewCarlson** [comment]
When the source code for 4.10.0 is published, you'll find all bintray repositories replaced.  The two missing dependencies redacted and walletkit are included as git submodules+composite gradle builds.

If you'd like to make the artifacts permanently available, publishing to a maven repository (like [Artifactory](https://jfrog.com/artifactory/)) is documented here: https://github.com/blockset-corp/walletkit/tree/core-6.2.2/WalletKitJava#publishing

Though to unblock yourself, checking out the core tag, running `./gradlew publishToMavenLocal`, and then adding the `mavenLocal()` repository is likely the quickest path forward.

**Comment by dabitdev** [comment]
Could I use `ZacSweers/redacted-compiler-plugin` (he has artifact at `repo.maven.apache.org/maven2`) or do I have to use your fork?

**Comment by DrewCarlson** [comment]
Resolved with the latest release, see https://github.com/breadwallet/brd-mobile
