### ISSUE TITLE
Imported Private Key sent to address not in Wallet

### ISSUE THREAD

**Issue by danaronoff** [breadwallet/breadwallet-android#23]
I may be missing something, but upon importing a private key from a paper wallet QR code I see the transaction was sent to an address that is not in the m/0'/0 derivation path I was expecting (and where my other wallet funds are). Is the address it was sent to on a different path?

**Comment by Gutyn** [comment]
try checking m/0'/1

**Comment by danaronoff** [comment]
Ah, perfect. Thanks.
