### ISSUE TITLE
 error: 'BRKey.h' file not found

### ISSUE THREAD

**Issue by byz0806** [breadwallet/breadwallet-android#24]
Error:C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\JNIBIP32Sequence.c:6:10: fatal error: 'BRKey.h' file not found
#include <BRKey.h>
         ^~~~~~~~~
1 error generated.

In file included from C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\core.c:27:
C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition/wallet.h:25:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^~~~~~~~~
1 error generated.

C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\JNIKey.c:6:10: fatal error: 'BRInt.h' file not found
#include <BRInt.h>
         ^~~~~~~~~
1 error generated.

C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\JNIBase58.c:7:10: fatal error: 'BRBase58.h' file not found
#include <BRBase58.h>
         ^~~~~~~~~~~~
1 error generated.

In file included from C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\wallet.c:25:
C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition/wallet.h:25:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^~~~~~~~~
1 error generated.

In file included from C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition\PeerManager.c:25:
C:\Users\Administrator\Desktop\breadwallet-android-master\breadwallet-android-master\app\src\main\jni\transition/PeerManager.h:26:10: fatal error: 'BRInt.h' file not found
#include "BRInt.h"
         ^~~~~~~~~
1 error generated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling JNIBIP32Sequence.c.
      C compiler failed while compiling core.c.
      C compiler failed while compiling JNIKey.c.
      C compiler failed while compiling JNIBase58.c.
      C compiler failed while compiling wallet.c.
      C compiler failed while compiling PeerManager.c.
  See the complete log at: file:///C:/Users/Administrator/Desktop/breadwallet-android-master/breadwallet-android-master/app/build/tmp/compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Gutyn** [comment]
Hi, try to do the steps from the installation process in ReadMe:
git submodule init
git submodule update
git submodule foreach git pull origin master

**Comment by byz0806** [comment]
thank you
