### ISSUE TITLE
Error: multiple definition of `BRBitcoinAmount'

### ISSUE THREAD

**Issue by byz0806** [breadwallet/breadwallet-android#25]
Information:Gradle tasks [:app:assembleDebug]
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\BRWallet.c
Error:(1197) multiple definition of `BRBitcoinAmount'
Error:(248) multiple definition of `BRLocalAmount'
Error:(248) multiple definition of `BRWalletAddressIsUsed'
Error:(248) multiple definition of `BRWalletAllAddrs'
Error:(248) multiple definition of `BRWalletAmountReceivedFromTx'
Error:(248) multiple definition of `BRWalletAmountSentByTx'
Error:(248) multiple definition of `BRWalletBalance'
Error:(248) multiple definition of `BRWalletBalanceAfterTx'
Error:(248) multiple definition of `BRWalletContainsAddress'
Error:(248) multiple definition of `BRWalletContainsTransaction'
Error:(248) multiple definition of `BRWalletCreateTransaction'
Error:(248) multiple definition of `BRWalletCreateTxForOutputs'
Error:(248) multiple definition of `BRWalletFeeForTx'
Error:(248) multiple definition of `BRWalletFeeForTxAmount'
Error:(248) multiple definition of `BRWalletFeeForTxSize'
Error:(248) multiple definition of `BRWalletFeePerKb'
Error:(248) multiple definition of `BRWalletFree'
Error:(248) multiple definition of `BRWalletMaxOutputAmount'
Error:(248) multiple definition of `BRWalletMinOutputAmount'
Error:(248) multiple definition of `BRWalletNew'
Error:(248) multiple definition of `BRWalletReceiveAddress'
Error:(248) multiple definition of `BRWalletRegisterTransaction'
Error:(248) multiple definition of `BRWalletRemoveTransaction'
Error:(248) multiple definition of `BRWalletSetCallbacks'
Error:(248) multiple definition of `BRWalletSetFeePerKb'
Error:(248) multiple definition of `BRWalletSetTxUnconfirmedAfter'
Error:(248) multiple definition of `BRWalletSignTransaction'
Error:(248) multiple definition of `BRWalletTotalReceived'
Error:(248) multiple definition of `BRWalletTotalSent'
Error:(248) multiple definition of `BRWalletTransactionForHash'
Error:(248) multiple definition of `BRWalletTransactionIsPending'
Error:(248) multiple definition of `BRWalletTransactionIsValid'
Error:(248) multiple definition of `BRWalletTransactionIsVerified'
Error:(248) multiple definition of `BRWalletTransactions'
Error:(248) multiple definition of `BRWalletTxUnconfirmedBefore'
Error:(248) multiple definition of `BRWalletUTXOs'
Error:(248) multiple definition of `BRWalletUnusedAddrs'
Error:(248) multiple definition of `BRWalletUpdateTransactions'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\BRBloomFilter.c
Error:(126) multiple definition of `BRBloomFilterContainsData'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\transition\JNIBase58.c
Error:(13) multiple definition of `Java_com_jniwrappers_BRBase58_base58Encode'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\BRCrypto.c
Error:(661) multiple definition of `BRChacha20'
Error:(76) multiple definition of `BRChacha20Poly1305AEADDecrypt'
Error:(76) multiple definition of `BRChacha20Poly1305AEADEncrypt'
Error:(76) multiple definition of `BRHMAC'
Error:(76) multiple definition of `BRHMACDRBG'
Error:(76) multiple definition of `BRHash160'
Error:(76) multiple definition of `BRMD5'
Error:(76) multiple definition of `BRMurmur3_32'
Error:(76) multiple definition of `BRPBKDF2'
Error:(76) multiple definition of `BRPoly1305'
Error:(76) multiple definition of `BRRMD160'
Error:(76) multiple definition of `BRSHA1'
Error:(76) multiple definition of `BRSHA224'
Error:(76) multiple definition of `BRSHA256'
Error:(76) multiple definition of `BRSHA256_2'
Error:(76) multiple definition of `BRSHA384'
Error:(76) multiple definition of `BRSHA512'
Error:(76) multiple definition of `BRScrypt'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\transition\wallet.c
Error:(757) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_addInputToPrivKeyTx'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_addressContainedInWallet'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_addressIsUsed'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_bitcoinAmount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_confirmKeySweep'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_createInputArray'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_createTxArrayWithCount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_createWallet'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_decryptBip38Key'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_encodeSeed'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_feeForTransaction'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getAddressFromPrivKey'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getAuthPrivKeyForAPI'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getAuthPublicKeyForAPI'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getBCashBalance'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getFirstAddress'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getMasterPubKey'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getMaxOutputAmount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getMinOutputAmount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getMinOutputAmountRequested'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getPrivKeyObject'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getReceiveAddress'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getSeedFromPhrase'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getTotalSent'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getTransactions'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_getTxCount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_isCreated'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_isTestNet'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_isValidBitcoinBIP38Key'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_isValidBitcoinPrivateKey'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_localAmount'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_publishSerializedTransaction'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_putTransaction'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_reverseTxHash'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_setFeePerKb'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_sweepBCash'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_transactionIsVerified'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_tryTransaction'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_validateAddress'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_validateRecoveryPhrase'
Error:(65) multiple definition of `Java_com_breadwallet_wallet_BRWalletManager_walletFreeEverything'
Error:(65) multiple definition of `callback'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\BRPeer.c
Error:(1532) multiple definition of `BRPeerAcceptMessageTest'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\BRBIP39Mnemonic.c
Error:(64) multiple definition of `BRBIP39Decode'
Error:(33) multiple definition of `BRBIP39DeriveKey'
Error:(33) multiple definition of `BRBIP39Encode'
Error:(33) multiple definition of `BRBIP39PhraseIsValid'
E:\MIAN_android\Qianbao\breadwallet-android\app\src\main\jni\breadwallet-core\test.c
Error:(1326) multiple definition of `BRAddressTests'
Error:(61) multiple definition of `BRArrayTests'
Error:(61) multiple definition of `BRAuthEncryptTests'
Error:(61) multiple definition of `BRBIP32SequenceTests'
Error:(61) multiple definition of `BRBIP38KeyTests'
Error:(61) multiple definition of `BRBIP39MnemonicTests'
Error:(61) multiple definition of `BRBase58Tests'
Error:(61) multiple definition of `BRBloomFilterTests'
Error:(61) multiple definition of `BRCypherTests'
Error:(61) multiple definition of `BRDrbgTests'
Error:(61) multiple definition of `BRHashTests'
Error:(61) multiple definition of `BRIntsTests'
Error:(61) multiple definition of `BRKeyTests'
Error:(61) multiple definition of `BRMacTests'
Error:(61) multiple definition of `BRMerkleBlockTests'
Error:(61) multiple definition of `BRPaymentProtocolEncryptionTests'
Error:(61) multiple definition of `BRPaymentProtocolTests'
Error:(61) multiple definition of `BRPeerTests'
Error:(61) multiple definition of `BRRunTests'
Error:(61) multiple definition of `BRSetTests'
Error:(61) multiple definition of `BRTransactionTests'
Error:(61) multiple definition of `BRWalletTests'
Error:(61) multiple definition of `main'
Error:(61) multiple definition of `syncStarted'
Error:(61) multiple definition of `syncStopped'
Error:(61) multiple definition of `txStatusUpdate'
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Error:Execution failed for task ':app:linkCoreArm64-v8aDebugSharedLibrary'.
> A build operation failed.
      Linker failed while linking libcore.so.
  See the complete log at: file:///E:/MIAN_android/Qianbao/breadwallet-android/app/build/tmp/linkCoreArm64-v8aDebugSharedLibrary/output.txt

**Comment by Gutyn** [comment]
Make sure you don't have duplicate jni folder in your app, remove the project and clone again.
Make sure to follow the readme steps.

**Comment by byz0806** [comment]
thank  you

08-09 09:03:51.386 3521-3521/com.breadwallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.breadwallet, PID: 3521
                                                               java.lang.NoClassDefFoundError: android.hardware.fingerprint.FingerprintManager
                                                                   at com.breadwallet.BreadWalletApp.onCreate(BreadWalletApp.java:87)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4346)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by Gutyn** [comment]
FingerprintManager is supported in API 23 and Higher.BreadWallet is only supporting android API23+ so if you want to support lower versions, please change the Fingerprint class to the respective one.

**Comment by voisine** [comment]
Lower apis are strongly unrecommended for security reasons. They are for-sure not suitable for anything more than pocket change amounts of digital currency.

**Comment by byz0806** [comment]
Thank you very much
