### ISSUE TITLE
Connect android breadwallet with Multichain

### ISSUE THREAD

**Issue by anastath** [breadwallet/breadwallet-android#26]
Hi, 

I want to connect the Android breadwallet app with a private [multichain ](https://www.multichain.com/)I have set up in localhost.
I have found some instructions on how to do this [here](https://github.com/voisine/breadwallet/issues/268), but this is not for the Android ported app.
Could you help me make the same modifications (DNS seeds, blockchain checkpoints, version message exchange) in the Android app source code?

Many thanks in advance!
Natassa

**Comment by jmacwhyte** [comment]
All of that is handled by [https://github.com/breadwallet/breadwallet-core](breadwallet core) .
DNS seeds and checkpoints are in BRPeerManager.c. Version messages are in BRPeer.c.

**Comment by anastath** [comment]
Hi again, 
I changed dns_seeds and checkpoints in BRPeerManager.c to match the parameters of the private Multichain node on my localhost.  I also changed STANDARD_PORT in BRPeer.h and PROTOCOL_VERSION and MIN_PROTO_VERSION  in the file BRPeer.c to match the parameters  of the private Multichain node on my localhost (The Multichain protocol version is 10008). 

Then I added in a new function to handle the verackack message used in Multichain Protocol during handhasking.` void BRPeerSendVerackackMessage(BRPeer *peer);`, similar to  BRPeerSendVerackMessage and call it properly (I can send you exact source if needed).

Then, I rebuilt the android-breadwallet project in Android Studio, and re-ran the app with Android Emulator, the device I use is Nexus 5X API 24. The breadwallet app started syncing and when reaching 5% got stuck and after a while 'not connected' appeared in red in the connected bar.

From the logs it seems that the app gets connected with the chain (the socket opens), but then, there is a problem with the version message exhanged and the connection is aborted and timed out. Can you give some hints on this problem?

The logs from the app are as follows (Actual IP and Port have been replaced below): 

> 08-28 12:22:21.167  6406  6567 D Message from C: : networkIsReachable
08-28 12:22:21.167  6406  6567 D Message from C: : getEnv peerManager
08-28 12:22:21.167  6406  6567 D com.breadwallet.wallet.BRPeerManager: networkIsReachable
08-28 12:22:21.167  6406  6567 I bread   : <IP:PORT> connecting
08-28 12:22:21.168  6406  6567 D Message from C: : txStatusUpdate
08-28 12:22:21.168  6406  6567 D Message from C: : getEnv peerManager
08-28 12:22:21.168  6406  6567 D com.breadwallet.wallet.BRPeerManager: txStatusUpdate
08-28 12:22:21.170  6406  6571 I bread   : <IP:PORT> socket connected
08-28 12:22:21.170  6406  6571 I bread   : <IP:PORT> sending version
08-28 12:22:21.171  6406  6572 D Message from C: : getTransactions
08-28 12:22:25.165  6406  6571 I bread   : <IP:PORT> Connection timed out
08-28 12:22:25.166  6406  6571 I bread   : <IP:PORT> disconnected
08-28 12:22:25.169  6406  6571 D Message from C: : networkIsReachable
08-28 12:22:25.169  6406  6571 D Message from C: : getEnv peerManager
08-28 12:22:25.169  6406  6571 D com.breadwallet.wallet.BRPeerManager: networkIsReachable
08-28 12:22:25.171  6406  6571 I bread   : <IP:PORT> connecting
08-28 12:22:25.171  6406  6571 D Message from C: : txStatusUpdate
08-28 12:22:25.171  6406  6571 D Message from C: : getEnv peerManager
08-28 12:22:25.171  6406  6571 D com.breadwallet.wallet.BRPeerManager: txStatusUpdate
08-28 12:22:25.174  6406  6575 I bread   : <IP:PORT> socket connected
08-28 12:22:25.174  6406  6576 D Message from C: : getTransactions
**08-28 12:22:25.174  6406  6575 I bread   : <IP:PORT> sending version
08-28 12:22:29.166  6406  6575 I bread   : <IP:PORT> Connection timed out**
08-28 12:22:29.166  6406  6575 I bread   : <IP:PORT> disconnected
08-28 12:22:29.166  6406  6575 I bread   : <IP:PORT> sync failed
08-28 12:22:29.166  6406  6575 D Message from C: : savePeers
08-28 12:22:29.166  6406  6575 D Message from C: : getEnv peerManager
08-28 12:22:29.166  6406  6575 D com.breadwallet.wallet.BRPeerManager: savePeers: 0
08-28 12:22:29.167  6406  6575 D Message from C: : getEnv peerManager
08-28 12:22:29.167  6406  6575 D com.breadwallet.wallet.BRPeerManager: syncFailed
08-28 12:22:29.167  6406  6575 D com.breadwallet.wallet.BRPeerManager: stopSyncingProgressThread
08-28 12:22:29.167  6406  6575 E com.breadwallet.wallet.BRPeerManager: Network Not Available, showing not connected bar  
08-28 12:22:29.168  6406  6466 E com.breadwallet.wallet.BRPeerManager: run: Thread.sleep was Interrupted
08-28 12:22:29.168  6406  6575 D com.breadwallet.wallet.BRPeerManager: stopSyncingProgressThread
08-28 12:22:29.168  6406  6575 D Message from C: : txStatusUpdate
08-28 12:22:29.168  6406  6575 D Message from C: : getEnv peerManager
08-28 12:22:29.168  6406  6575 D com.breadwallet.wallet.BRPeerManager: txStatusUpdate
08-28 12:22:29.171  6406  6584 D Message from C: : getTransactions

**Comment by HenryChou007** [comment]
@anastath   Have you solved your problem ？

**Comment by HenryChou007** [comment]
@anastath  Have you solved your problem ？
