### ISSUE TITLE
Disable protocol version check when connecting with remote peer

### ISSUE THREAD

**Issue by anastath** [breadwallet/breadwallet-android#27]
Hi all,
I'm in the process of connecting the android breadwallet app with a private [multichain ](https://www.multichain.com/)which I have set up  on my localhost. In the mobile device where the breadwallet app runs, the connection **keeps syncing (until 5%)** and **gets stuck** without either connecting or displaying the message 'not connected'.

In the Multichain logs I can see that the connection gets stuck when the minimum parameter set is sent from the Multichain node to the breadwallet node. I suppose the problem is that the breadwallet app can't accept the protocol version of the Multichain node (10008). 
Multichain developers propose to 

> Ensure the wallet accepts the protocol-version which is defined on your chain, or remove the check completely to allow your protocol to be upgraded in future.

The question is, **how can I completely remove the check for the version  of the remote peer within the breadwallet android code**? Many thanks in advance for your help!

Regards,
Natassa

**Comment by Gutyn** [comment]
The check happens in 

> BreadWallet/app/src/main/jni/breadwallet-core/BRPeer.c

Please take a look there.
