### ISSUE TITLE
light header makes it unreadable

### ISSUE THREAD

**Issue by Deluxo** [breadwallet/breadwallet-android#29]
### Hello.

In the screenshot you can see the **header has white background with white text**. It makes the content **unreadable**.
Can you tweak this?

Also, will there be a **dark mode?** I'd really appreciate a dark interface...

Thanks!

Phone info:

* ZTE BLADE V0720 (lite)
* Android 6.0
* Kernel 3.18.19
* App version 97

![screenshot_20170830-004513](https://user-images.githubusercontent.com/3360414/29845832-fb06c92e-8d1c-11e7-8cc3-f05ee7c61380.png)

**Comment by Gutyn** [comment]
Thanks for sharing, we will fix it as soon as possible.

**Comment by Gutyn** [comment]
This is fixed in the new redesign app that is in beta at the moment, coming to public release soon.
