### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Rumhocker** [breadwallet/breadwallet-android#3]
Please test following: 
-go to "request an amount"
-write some Bitcoin
-change Bitcoin to Euro (or your curency)
The app will chrash. I have tested with HTC M8 and Samsung S5

![screenshot1 mobile](https://cloud.githubusercontent.com/assets/9468349/17555067/4deb61f6-5f0e-11e6-8aec-52658dba1b8d.png)

**Comment by Gutyn** [comment]
Thanks for the report @Rumhocker, can I ask you what version of the app you're using and what is the amount in bits when you swap the currencies? Thanks.

**Comment by Kirvx** [comment]
Same here with my Z3 Compact, version 23

**Comment by Gutyn** [comment]
@Kirvx @Rumhocker is the problem still there after the new version 31 update? if it is please report it once it crashes. I need the logs, can't see obvious any problem in there.

**Comment by Kirvx** [comment]
Fixed for me, thanks.

**Comment by Gutyn** [comment]
awesome, then I will close the issue for now. Thanks.
