### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jomnes** [breadwallet/breadwallet-android#31]
Hi, I am having some trouble running the breadwallet-android project in Android Studio.  I get the following error:

A build operation failed.
      C compiler failed while compiling BRBIP32Sequence.c.

Information:Gradle tasks [:app:assembleDebug]
Information:(Unknown) In file included
C:\wallet\breadwallet-android\app\src\main\jni\breadwallet-core\BRBIP32Sequence.h
Error:(76, 83) error: unknown type name 'va_list'
Information:(Unknown) In file included
C:\wallet\breadwallet-android\app\src\main\jni\breadwallet-core\BRCrypto.h
C:\wallet\breadwallet-android\app\src\main\jni\breadwallet-core\BRBIP32Sequence.c
Error:Execution failed for task ':app:compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC'.
> A build operation failed.
      C compiler failed while compiling BRBIP32Sequence.c.
  See the complete log at: file:///C:/wallet/breadwallet-android/app/build/tmp/compileCoreArm64-v8aDebugSharedLibraryCoreArm64-v8aDebugSharedLibraryMainC/output.txt
Information:BUILD FAILED
Information:Total time: 12.65 secs
Information:2 errors
Information:6 warnings
Information:See complete output in console

Any help would be greatly appreciated

Jomnes

**Comment by Gutyn** [comment]
va_list is part of the Android toolchain, please make sure you have android toolchain installed or updated.

**Comment by jomnes** [comment]
Hi, I was able to get it working by hovering over va_list and pressing Alt+Enter.
