### ISSUE TITLE
impossible to recover

### ISSUE THREAD

**Issue by sknsean** [breadwallet/breadwallet-android#32]
After i put in my recovery phase, the android apps tries to authenticate in android.
If I scan my finger or I type my unlock code it just jumps back to the authenticate screen again.

Device: Xiaomi A1 (Android One) version 7.1.2

**Comment by Gutyn** [comment]
Thanks for reporting this rare bug, @sknsean, have you tried uninstalling the wallet?

**Comment by sknsean** [comment]
No, but the phone is only 1 week old, and freshly installed. Does it work in the emulator with android 7.1.2. If you can't replicate it. I could wait for Google updating the phone...

**Comment by Gutyn** [comment]
This is a rare KeyStore bug that we've been unable to reproduce yet. We will investigate the problem, thank you. Please feel free to report any information that might help us.

**Comment by bryanbecker** [comment]
I'm having the same issue with my phone

New LG K20

**Comment by bryanbecker** [comment]
Updating that the issue persists on the new android beta

**Comment by Gutyn** [comment]
@bryanbecker we appreciate your feedback, have you tried uninstalling the app? The issue persists? This seems like an android KeyStore bug but we're working on finding a solution. Thanks.

**Comment by bryanbecker** [comment]
I tried first deleting all application data and retrying, but that didn't work.

Just tried a complete uninstall / reinstall.  When prompted to recover wallet, after entering the 12 key words, this time I get:

```
Android KeyStore Error

Failed to load KeyStore(phrase). Please try to again later or enter your phrase to recover your Bread now.
```

This drops me back to submit the 12 key words.  After hitting submit a 2nd time, the "Authentication required" loop from the OP starts

**Comment by vypr** [comment]
Same incident with trying to make a new wallet on Android 7.0, LG Stylo 3

**Comment by skny-prevas** [comment]
Same issue after the new update :-) Do you have one of the affected devices to test on? Are you able to reproduce the bug?

**Comment by sknsean** [comment]
Same issue after the new update :-) Do you have one of the affected devices to test on? Are you able to reproduce the bug?

**Comment by Gutyn** [comment]
@sknsean  we do have the affected device but no luck in reproducing it whatsoever, unfortunately.

**Comment by Gutyn** [comment]
@sknsean while having breadwallet installed:
1) have you modified any fingerprints (add, remove)? 
2)Also, have does deleting and reinstalling the wallet not help? 
3) Does removing the screen lock all-together and reenabling it fixes the problem?
Thanks for the help in advance.

**Comment by sknsean** [comment]
Removing fingerprints and the screen lock and reenabling it solves the problem :-)

**Comment by Gutyn** [comment]
@sknsean thanks for your help, this information will be useful, we are working on the issue.

**Comment by sknsean** [comment]
After setup of fingerprints, closing the app and reopening, the app shows the keystore error again and we are knocked back to start again :-)

**Comment by Gutyn** [comment]
@sknsean I've come across some google docs that state a known keystore issue that is causing this, we might have a potential fix our public beta channel by the end of the week. Thanks for your help.

**Comment by sknsean** [comment]
Hi I'm on version 165, now I don't get an error but after typing my recover words nothing happens when I press "Next".

**Comment by Gutyn** [comment]
@sknsean thank you for your help! I tend to think your phone's Keystore is in a malformed state or you're experiencing an android bug, are you willing to be a part of our closed beta so I can try and add different solutions to the wallet and you could try it? Have you saved your paper key?

**Comment by skny-prevas** [comment]
@Gutyn yes i'm willing to help :-) Yes i have it backed up.

**Comment by sknsean** [comment]
@Gutyn yes i'm willing to help :-) Yes i have it backed up.

**Comment by Gutyn** [comment]
@sknsean I very much appreciate your help. Will let you know when I have a potential solution. Have a great day.

**Comment by Gutyn** [comment]
@sknsean The research to date shows that this is a known rare android Keystore issue with some Android phones, also I ordered the Xiaomi A1 (Android One) to test it closely and come up with a possible solution. Meanwhile, you could try something for me:
1) Remove all fingerprints and the screen lock, then re-enable the screen lock AND add fingerprints, now when you are all done, try to reinstall Bread and use it, the point here is to not have ANY modification to the device security after you created the wallet (thus, the keys). 
Please let me know if this is a working temporary solution.
Thanks for your help, @sknsean

**Comment by sknsean** [comment]
@Gutyn just tested this, it's the same as before. It seems like the issue is related to the fingerprints, without any fingerprints stored it works just fine.

**Comment by Gutyn** [comment]
@sknsean thanks a lot for your help, yes, it does look like a Keystore problem related to fingerprints. Will keep you updated.

**Comment by sknsean** [comment]
An update, even after the phone got updated to Android O/Oreo the Keystore problem persists :-(
Any news on a possible fix?

**Comment by Gutyn** [comment]
@sknsean Thanks for the info, my next task today is working on the endless auth in the keystore.
Can you please tell me if your phone has the lock screen on? (PIN, password or pattern) ?

**Comment by Gutyn** [comment]
@sknsean this seems to be an Android bug and their team has communicated the plan to fix that in android 8.+, can you please update your OS version and let me know if that fixes the problem?

**Comment by sknsean** [comment]
Hi :-) Fixed? 
Where is the wallet app? I can't find it on the play store

**Comment by Gutyn** [comment]
Hi @sknsean if you don't see the app that means you're in Europe and our app was pulled off the market due to some legal issues that are fixed now so you should be able to see it as soon as google unlocks it

**Comment by skny-prevas** [comment]
Issue still present... Why is it closed?

**Comment by sknsean** [comment]
Issue still present... Why is it closed?

**Comment by vypr** [comment]
^ My provider nor my phone manufacturer has an update out for 8.0, so it really just passes the blame.

**Comment by Gutyn** [comment]
The issue is caused by an OS bug that we have no power over. It still remains one of our priorities to find a workaround or better instruct the user on the precaution steps.

**Comment by sknsean** [comment]
Okay :-) Thank for your support. Do you a explanation or some links i can send to xiaomi?

**Comment by Gutyn** [comment]
One example of the Keystore being weird:
https://issuetracker.google.com/issues/69786239
The KeyStore keeps throwing an exception that the user is not Authenticated (even after authentication) that is what happens in your device that is causing an authentication loop.

There is a possible solution for your phone that I was able to use on some user:
-Uninstall the wallet.
-Remove the home lock screen
-Remove ALL fingerprints
-Install the home lock screen (PIN, Password or Pattern)
-Install all the needed fingerprints
-Install BreadWallet again 

I observed this solution to help as long as you don't touch the fingerprint settings (no addition, modification or removal of fingerprints)
