### ISSUE TITLE
Add support for sending to BIP173 addresses

### ISSUE THREAD

**Issue by Walter-Bishop** [breadwallet/breadwallet-android#33]
[BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) ("bech32") enables native segwit transactions on the Bitcoin network. Using it will allow for smaller on-chain transactions. For bech32-addresses to gain adoption, wallet support is needed.

Please add support for sending to BIP173 addresses.

There are multiple reference implementation here: https://github.com/sipa/bech32/tree/master/ref/ (sadly none for Java).

**Comment by Gutyn** [comment]
Thanks for sharing. We are working on many features while trying to balance their priorities, we will totally look into it.
