### ISSUE TITLE
(bug) workaround to PIN lockout time

### ISSUE THREAD

**Issue by jyk88** [breadwallet/breadwallet-android#34]
Some relevant info:
Version: 165
Phone: Nexus 6P

Details of bug:
I recently forgot my pin and ended up locking myself out of my wallet. I tried enough times to lock myself out for more than three hours.

I discovered that if I click the "reset pin" button that takes me to an input for the pass phrase. At that page, I can hit the back button and it takes me right back to the pin screen, which allows me to try the pin again, as if I wasn't locked out. 

This means I can keep trying the pin, infinitely, without getting locked out of the wallet. 

I know that I didn't get locked out because I remembered my pin a few minutes later and it worked when I should have been locked for another three hours.

Thank you! Please let me know if this should be in a certain format, happy to re-write it.

**Comment by Gutyn** [comment]
@jyk88 Thank you for reporting this bug, I will work on a fix today and have a beta build by the end of the day.
