### ISSUE TITLE
App crashes when withdrawing BCH - Version 165

### ISSUE THREAD

**Issue by darko-mijic** [breadwallet/breadwallet-android#35]
I am using Bread wallet version 165 for Android and I have an issue with BCH withdrawal.
Every time I enter or scan the destination address wallet crashes.

I have tried removing local data from the wallet and restoring it from the seed but that did not help.

Are you aware of this issue and is there a way around it?

**Comment by Gutyn** [comment]
Hi @darko-mijic, I possible fix was in beta 167 so far, the public production rollout started today, you will get the new version soon, please let me know if you still have difficulties.

**Comment by darko-mijic** [comment]
Hi @Gutyn. Thanks for the reply.
I have version 167 and I have the same issue.

**Comment by Gutyn** [comment]
@darko-mijic thanks for helping, I am unable to see any reports of any crashes in the BCH view does the issue happen when you click on "Paste"? Can you please try again so maybe the report shows up. Thanks.

**Comment by darko-mijic** [comment]
It worked with pasting the address. It was crashing after scanning the address.

There are three issues with this feature @Gutyn:
- App crashes after scanning the address.
- BCH amount is completely wrong. I had around 100 USD there, 2 versions ago it was displaying millions and with current versions around 10x. Probably the price of BTC instead of BCH.
- App crashes after successful BCH withdrawal. Screenshot attached.

![screenshot_20171214-130026](https://user-images.githubusercontent.com/4280521/33991510-2d02dbb0-e0cf-11e7-88ef-9887ab1ff7be.jpg)

**Comment by Gutyn** [comment]
@darko-mijic Thanks again for your help, I've reproduced the bugs and fixed. The fix will come out in the next 169 version. 
Best regards
