### ISSUE TITLE
writing in app

### ISSUE THREAD

**Issue by Rumhocker** [breadwallet/breadwallet-android#4]
if you tap under "pay adress from clipboard" your keyboard open and you can write in app.

![screenshot2 mobile](https://cloud.githubusercontent.com/assets/9468349/17555158/cdeb5fa0-5f0e-11e6-94d0-065a7fe44264.png)

**Comment by Gutyn** [comment]
The reason for this edit text is to write down an address manually and then hit "pay address from clipboard" and if the address inserted in this edit text is a valid address then it will open the send screen.

**Comment by voisine** [comment]
yes, it's kind of hidden because manually entering an address is not what we expect users to do, but the functionality is there if needed
