### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by andmizi** [breadwallet/breadwallet-android#41]
hi:
Information:(326, 21) include the header <stdlib.
h> or explicitly provide a declaration for 'calloc'
C:\Users\kimi\Desktop\skycoin\breadwallet-android\app\src\main\jni\transition\wallet.c:543:20: warning: implicitly declaring library function 'malloc' with type 'void *(unsigned long)' [-Wimplicit-function-declaration]
Information:(543, 20) include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
C:\Users\kimi\Desktop\skycoin\breadwallet-android\app\src\main\jni\transition\wallet.c:568:28: warning: implicit declaration of function 'u256_hex_decode' is invalid in C99 [-Wimplicit-function-declaration]
Error:(568, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(583, 73) warning: format specifies type 'long long' but the argument has type 'jlong' (aka 'long') [-Wformat]
Warning:(591, 66) warning: format specifies type 'long long' but the argument has type 'jlong' (aka 'long') [-Wformat]
Warning:(699, 33) warning: format spec
Error:(857, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(860, 38) warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
Warning:(876, 38) warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
Error:(886, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(893, 11) warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
Warning:(139, 27) warning: implicit declaration of function 'u256_hex_encode' is invalid in C99 [-Wimplicit-function-declaration]
Warning:(893, 11) warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
please help me,thx

**Comment by Gutyn** [comment]
Try now

**Comment by morganchia** [comment]
Hi, 
I am still having this issue although i have executed git submodule update and restarted Android Studio.

Information:Gradle tasks [:app:assembleBreadDebug]
C:\Users\xxx\Documents\AndroidStudio\breadwallet-android\app\src\main\jni\breadwallet-core\BRKey.c
Warning:(51, 32) warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-pragmas]
Warning:(51, 32) warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-pragmas]
C:\Users\xxx\Documents\AndroidStudio\breadwallet-android\app\src\main\jni\transition\wallet.c
Warning:(139, 27) warning: implicit declaration of function 'u256_hex_encode' is invalid in C99 [-Wimplicit-function-declaration]
Warning:(139, 17) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(161, 21) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(178, 17) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(253, 13) warning: implicit declaration of function 'free' is invalid in C99 [-Wimplicit-function-declaration]
Warning:(326, 21) warning: implicitly declaring library function 'calloc' with type 'void *(unsigned int, unsigned int)' [-Wimplicit-function-declaration]
Warning:(526, 45) warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
Warning:(543, 20) warning: implicitly declaring library function 'malloc' with type 'void *(unsigned int)' [-Wimplicit-function-declaration]
Information:(543, 20) include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
C:\Users\xxx\Documents\AndroidStudio\breadwallet-android\app\src\main\jni\transition\wallet.c:568:28: warning: implicit declaration of function 'u256_hex_decode' is invalid in C99 [-Wimplicit-function-declaration]
Error:(568, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Error:(857, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(860, 38) warning: incompatible integer to pointer c
Warning:(876, 38) warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
Error:(886, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(893, 11) warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
Warning:(139, 27) warning: implicit declaration of function 'u256_hex_encode' is invalid in C99 [-Wimplicit-function-declaration]
Warning:(139, 17) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(161, 21) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(178, 17) warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
Warning:(253, 13) warning: implicit declaration of function 'free' is invalid in C99 [-Wimplicit-function-declaration]
Warning:(326, 21) warning: implicitly declaring library function 'calloc' with type 'void *(unsigned int, unsigned int)' [-Wimplicit-function-declaration]
Information:(326, 21) note: include the header <stdlib.h> or explicitly provide a declaration for 'calloc'
Warning:(526, 45) warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
Warning:(543, 20) warning: implicitly declaring library function 'malloc' with type 'void *(unsigned int)' [-Wimplicit-function-declaration]
Information:(543, 20) note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
Warning:(568, 28) warning: implicit declaration of function 'u256_hex_decode' is invalid in C99 [-Wimplicit-function-declaration]
Error:(568, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Error:(857, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(860, 38) warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
Warning:(876, 38) warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
Error:(886, 13) error: initializing 'UInt256' with an expression of incompatible type 'int'
Warning:(893, 11) warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
Information:BUILD FAILED in 2m 6s
Information:6 errors
Information:25 warnings
Information:See complete output in console
