### ISSUE TITLE
Question: TestNet support

### ISSUE THREAD

**Issue by Neustart** [breadwallet/breadwallet-android#43]
Hi there !
I want to test wallet using TestNet network, how can I use you wallet with TestNet ?
I've added testnet node, but where I can find QR code or my wallet address ?
Thanks

**Comment by Gutyn** [comment]
Hi, you can just switch to the *breadTestnetDebug* Build Variant and it will magically work.

**Comment by ianeinser** [comment]
@Gutyn 

> Hi, you can just switch to the _breadTestnetDebug_ Build Variant and it will magically work.

may i know how i can do so?

**Comment by Gutyn** [comment]
you Have to go to the `Build Variants` TAB on the left and chose the build Variant called
`brdTestnetDebug`. Then if you run the app, you will have a separate app in your device callet BrdTestnet.
