### ISSUE TITLE
Why it does not work, 23 api level and lower ?

### ISSUE THREAD

**Issue by berycoin-project** [breadwallet/breadwallet-android#45]
Hey 

I recently wanted to compile the code. for myself, 
and it seems to be like , it won't work on devices that have lower version of sdk
like here. on virtual device. api level above 25 it works.. 
red line. api level 22 it won't work ... 

what do i need , in order to make it work with that.. and even lower api levels ?

![capture](https://user-images.githubusercontent.com/32966245/36064089-9e8b93a2-0ea7-11e8-9402-12f3c5b7339e.JPG)

**Comment by Jurdefur** [comment]
The minimum SDK is 23 and above and its not backwards compatible with older android versions.

**Comment by Gutyn** [comment]
The minimum security level needed for a noncustodial wallet that needs to store the private keys locally (in the KeyStore) is provided in android 6.0 and up.
