### ISSUE TITLE
API < 23?

### ISSUE THREAD

**Issue by rraallvv** [breadwallet/breadwallet-android#46]
Any chances of adding support for previous version of Android than those with API level 23?

I'm asking because it seems there is a [support library](https://developer.android.com/reference/android/support/v4/hardware/fingerprint/package-summary.html) with the FingerprintManager class, although I haven't tried it myself.

**Comment by rraallvv** [comment]
I was able to build and run the app on Android 4.0.3 (API 15) on the emulator using the support libraries, it needs testing though to see if everything run smoothly.

**Comment by Gutyn** [comment]
@rraallvv we don't support lower versions (and will never do) due to the security level needed for an SPV wallet provided in 23+ since we're storing the private key locally. Thanks for asking.
