### ISSUE TITLE
Can't use program because no screen lock, but it's not a risk

### ISSUE THREAD

**Issue by dhjw** [breadwallet/breadwallet-android#49]
I would like to use the app but I can't load it because of the screen lock restriction. I get the message "A device screen lock is needed to safeguard your wallet." and can't continue.

I do in fact have a screen lock set up but I'm using the "Delayed Lock" app to temporarily disable it based on being connected to my local wifi.

I suppose there's no way to run the BRD wallet when this app is disabling the screen lock.

Please consider detecting temporarily disabled screen locks, if possible, and allowing the app to run. Alternatively, please add an option to bypass the check.

Thanks

**Comment by Gutyn** [comment]
Hi @dhjw, our app uses the Android Keystore for sensitive information like your private key which is not something you can afford to lose, and the lock screen protects it from potential malware (The Keystore is available only 5 minutes after the last pin/password/pattern use which helps keep your sensitive data secure). So without a lock screen, the Keystore would just fail to initialize.
