### ISSUE TITLE
error: "Please select num implementation"

### ISSUE THREAD

**Issue by Rumhocker** [breadwallet/breadwallet-android#5]
I would make my own app with android studio.
But i cannot "Make Project", i become this: error: "Please select num implementation"
Is there someone who knows where this error comes from?

![bereich](https://cloud.githubusercontent.com/assets/9468349/18555551/959de07a-7b68-11e6-9d42-55a2f89facb0.jpg)

**Comment by Gutyn** [comment]
Hey Rumhocker, sorry for the late response, please try to init the submodules and update them, then delete the content from the folder:  .../BreadWallet/app/src/main/jni/breadwallet-core/secp256k1, then do a rebuild, let me know if it fixes the problem, I will update the instruction on installation soon.

**Comment by Rumhocker** [comment]
Big thanks for the hint. I copied the submodules by hand and no seen that submodule is in a DETACHED state.
Step1:
`git submodule update --init`
This will allow me to do git submodule init and git submodule update in one step. But the problem is i get a "Permission denied". 
Step2:
So i have change the git@github.com:breadwallet/.... to https://github.com/breadwallet/... in the config file in .git folder. 

I thing there exist an easier way but whatever now the App is running.

**Comment by Gutyn** [comment]
Glad I could help, enjoy.

**Comment by Rumhocker** [comment]
Now i have a german version...
