### ISSUE TITLE
breadwallet-android\app\src\main\jni\breadwallet-core\BRAddress.c

### ISSUE THREAD

**Issue by niewenlong123** [breadwallet/breadwallet-android#50]
C:\Users\niewenlong\Documents\GitHub\breadwallet-android\app\src\main\jni\breadwallet-core\BRAddress.c
Error:(281) undefined reference to BRBech32Encode' Error:(378) undefined reference toBRBech32Decode'
Error:(404) undefined reference to `BRBech32Decode'
I don't know what the problem is. I want to ask you to help you. Thank you.

**Comment by Gutyn** [comment]
Fixed
