### ISSUE TITLE
Make standalone APK available from the Github releases page

### ISSUE THREAD

**Issue by leafcutterant** [breadwallet/breadwallet-android#56]
Feature request.

**Comment by PanderMusubi** [comment]
To support this issue, a request for packaging has been made at F-Droid, please see https://gitlab.com/fdroid/rfp/issues/604

**Comment by PanderMusubi** [comment]
Unfortunately, there are too many binaries as you can see via the link above. An alternative is to setup an F-Droid for this app like e.g. http://www.cgeo.org/ has done.

**Comment by Gutyn** [comment]
@PanderMusubi we are discussing this matter today, thank you.

**Comment by leafcutterant** [comment]
> Gutyn closed this on Jun 13, 2018

@Gutyn will you please *not* close issues until they are solved, especially when it's not settled for 2+ years afterwards? Thank you. I'm requesting a re-opening.

**Comment by DrewCarlson** [comment]
@leafcutterant If your original request is still unresolved, open a new issue and we can discuss it.  Please be descriptive as it's unclear what you're requesting here.  If this is about F-Droid/Play Services then see [here](https://github.com/breadwallet/breadwallet-android/issues/102#issuecomment-699091147).
