### ISSUE TITLE
Have Breadwallet listed on F-Droid

### ISSUE THREAD

**Issue by leafcutterant** [breadwallet/breadwallet-android#57]
Raise the trustworthiness of the app by adding it to F-Droid.

[Inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/)

[Inclusion How-To](https://f-droid.org/en/docs/Inclusion_How-To/)

**Comment by Gutyn** [comment]
Thanks for your recommendation, we'll consider that in the future.

**Comment by ghbjklhv** [comment]
@Guttyn One key issue to get Bread Wallet listed in F-Droid is:

>  The original app author has been notified (and supports the inclusion).

Do ya'll support the inclusion?

**Comment by trymeouteh** [comment]
Please remove the Crashlytics and Firebase.
