### ISSUE TITLE
question on adding a new coin

### ISSUE THREAD

**Issue by tofutim** [breadwallet/breadwallet-android#58]
Hi, I'm experimenting with adding a new coin. However, even though I'm pulling blocks from block #1, they all get relegated to orphan status because I have no 'prev'. Is there something you do to place the genesis block so that this doesn't happen? I'm totally perplexed.

In `_peerRelayedBlock(void *info, BRMerkleBlock *block)`, where you have
```
    prev = BRSetGet(manager->blocks, &block->prevBlock);

    if (prev) {
        txTime = block->timestamp/2 + prev->timestamp/2;
        block->height = prev->height + 1;
    }
```
I have no blocks, so prev is always null, even though the first block I get from the server is the one where the prevblock hash is the genesis hash...

(or maybe you never start from the beginning?)

*Update.* I think I see it here
```

    for (size_t i = 0; i < manager->params->checkpointsCount; i++) {
        block = BRMerkleBlockNew();
        block->height = manager->params->checkpoints[i].height;
        block->blockHash = UInt256Reverse(manager->params->checkpoints[i].hash);
        block->timestamp = manager->params->checkpoints[i].timestamp;
        block->target = manager->params->checkpoints[i].target;
        BRSetAdd(manager->checkpoints, block);
        BRSetAdd(manager->blocks, block);
        if (i == 0 || block->timestamp + 7*24*60*60 < manager->earliestKeyTime) manager->lastBlock = block;
    }
```
maybe my checkpoints are defined correctly....

**Comment by Gutyn** [comment]
We don't always start from the beginning, only on a fresh install and then save the blocks to the local client's DB and then pass them in the next launch to minimize the syncing time.

**Comment by tofutim** [comment]
I found the issue, and it is a mysterious. When _peerRelayedBlock is called, somehow my block gets scrambled. Before the call the block has version = 6, but when it gets into _peerRelayedBlock the version is 65541 and the rest of the data is scrambled also. Very strange.

**Comment by Gutyn** [comment]
This is the android project, please consider to create issues in the core project:
https://github.com/breadwallet/breadwallet-core
