### ISSUE TITLE
BCH BIP-70 Support

### ISSUE THREAD

**Issue by zquestz** [breadwallet/breadwallet-android#60]
Please add BIP-70 support for BCH. Many users need this to pay at BitPay supported merchants!

**Comment by zquestz** [comment]
Any time frame? I heard from a little bird this was nearly complete. =)

**Comment by Gutyn** [comment]
@zquestz BIP-70 is supported for both BTC and BCH in BRD unless you encounter a bug.

**Comment by zquestz** [comment]
This is incorrect. BIP-70 fails to work on my Android build. It scans it, then closes the send window immediately with no funds sent. I can confirm this is happening to other users as well.

**Comment by zquestz** [comment]
Also notice this page -> https://support.bitpay.com/hc/en-us/articles/115005701523-Which-wallets-work-for-a-BitPay-payment-Which-wallets-are-compatible-

Shows it only works for BTC, which it does. BCH is not working currently.

**Comment by zquestz** [comment]
Thank you for the quick reply. Really appreciate it!

**Comment by zquestz** [comment]
Release from today still does not work. Just a heads up.

**Comment by imaginaryusername** [comment]
Will like to see this fixed and usable too.

**Comment by zander** [comment]
I've been waiting for this support for some time. Just found this issue. Please add my vote to get this in.

**Comment by TheDerrickJ** [comment]
Same issue. BTC and BCH failing to send correctly with BRD wallet and Bip70 requests or even JSON style payment requests. It can read them but then somehow sends incorrectly. Something is messed up.
