### ISSUE TITLE
Support UI Glitches / Missing Content

### ISSUE THREAD

**Issue by zquestz** [breadwallet/breadwallet-android#61]
Right now the support section has padding and layout issues. Headers on all the pages are covered by the header, and there is almost no content about BCH.

This should be a minor change, and will lead to a much more polished UI.

**Comment by zquestz** [comment]
Latest beta had a regression that broke several images on the main page.

**Comment by zquestz** [comment]
Now images are fixed, but there is no way to go back as the back icon in the header was removed.

**Comment by Gutyn** [comment]
Thank you for your contribution, we'll improve our UI experience.
