### ISSUE TITLE
Error when build project

### ISSUE THREAD

**Issue by ductuan10081992** [breadwallet/breadwallet-android#66]
Hi everybody. I am trying to build a project on my computer and encounter this error when I build. Hope everybody help please

I installed the latest NDK

error:
Build command failed.

Error while executing process C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app -BC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\.externalNativeBuild\cmake\brdRelease\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\build\intermediates\cmake\brd\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17 -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DCMAKE_TOOLCHAIN_FILE=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: C:/Users/A/Desktop/breadwallet/breadwallet-android-master/app/.externalNativeBuild/cmake/brdRelease/armeabi-v7a

Build command failed.

Error while executing process C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app -BC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\.externalNativeBuild\cmake\brdTestnetDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\build\intermediates\cmake\brdTestnet\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17 -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DCMAKE_TOOLCHAIN_FILE=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: C:/Users/A/Desktop/breadwallet/breadwallet-android-master/app/.externalNativeBuild/cmake/brdTestnetDebug/armeabi-v7a

Build command failed.

Error while executing process C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app -BC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\.externalNativeBuild\cmake\brdDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\build\intermediates\cmake\brd\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17 -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DCMAKE_TOOLCHAIN_FILE=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: C:/Users/A/Desktop/breadwallet/breadwallet-android-master/app/.externalNativeBuild/cmake/brdDebug/armeabi-v7a

Build command failed.

Error while executing process C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app -BC:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\.externalNativeBuild\cmake\brdTestnetRelease\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\A\Desktop\breadwallet\breadwallet-android-master\app\build\intermediates\cmake\brdTestnet\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17 -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DCMAKE_TOOLCHAIN_FILE=C:\Users\A\Desktop\android-ndk-r17\android-ndk-r17\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\A\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/A/Desktop/android-ndk-r17/android-ndk-r17/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: C:/Users/A/Desktop/breadwallet/breadwallet-android-master/app/.externalNativeBuild/cmake/brdTestnetRelease/armeabi-v7a

**Comment by Gutyn** [comment]
Make sure you follow the build instructions in README and update the git submodules.
