### ISSUE TITLE
Cmake and NDK issue

### ISSUE THREAD

**Issue by essujith** [breadwallet/breadwallet-android#68]
i downloaded the code and installed ndk,cmake then i build the project i am getting this error please help me if anyone knows 

Build command failed.

Error while executing process E:\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\user\breadwallet-android-master\app -BE:\user\breadwallet-android-master\app\.externalNativeBuild\cmake\brdTestnetDebug\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\user\breadwallet-android-master\app\build\intermediates\cmake\brdTestnet\debug\obj\x86 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=E:\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DCMAKE_TOOLCHAIN_FILE=E:\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: E:/usern/breadwallet-android-master/app/.externalNativeBuild/cmake/brdTestnetDebug/x86

Build command failed.

Error while executing process E:\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\user\breadwallet-android-master\app -BE:\user\breadwallet-android-master\app\.externalNativeBuild\cmake\brdDebug\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\user\breadwallet-android-master\app\build\intermediates\cmake\brd\debug\obj\x86 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=E:\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DCMAKE_TOOLCHAIN_FILE=E:\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: E:/user/breadwallet-android-master/app/.externalNativeBuild/cmake/brdDebug/x86

Build command failed.

Error while executing process E:\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\user\breadwallet-android-master\app -BE:\user\breadwallet-android-master\app\.externalNativeBuild\cmake\brdTestnetRelease\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\user\breadwallet-android-master\app\build\intermediates\cmake\brdTestnet\release\obj\x86 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=E:\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=1 -DCMAKE_TOOLCHAIN_FILE=E:\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: E:/user/breadwallet-android-master/app/.externalNativeBuild/cmake/brdTestnetRelease/x86

Build command failed.

Error while executing process E:\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\user\breadwallet-android-master\app -BE:\user\breadwallet-android-master\app\.externalNativeBuild\cmake\brdRelease\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\user\breadwallet-android-master\app\build\intermediates\cmake\brd\release\obj\x86 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=E:\Sdk\ndk-bundle -DCMAKE_C_FLAGS=-DBITCOIN_TESTNET=0 -DCMAKE_TOOLCHAIN_FILE=E:\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=gnustl_static}

 (include)   CMakeLists.txt 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

 (project) 

-- Check for working C compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: E:/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

CMake Error at CMakeLists.txt:23 (add_library):

    src/main/jni/breadwallet-core/BRAddress.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: core

-- Generating done

-- Build files have been written to: E:/user/breadwallet-android-master/app/.externalNativeBuild/cmake/brdRelease/x86

**Comment by vegasQC777** [comment]
1DC5Gy3pdqud9ZUAfmX3qAiQ8Tdw9xVYbh

**Comment by Gutyn** [comment]
Make sure you follow the setup instructions in ReadMe.

**Comment by coderabbitcrypto** [comment]
@Gutyn 
Have tried both ways but still nothing, gonna try to reinstall cmake and the NDK again

**Comment by coderabbitcrypto** [comment]
still the same, I'll continue trying to figure it out here, If I managed to clear that I'll post here the solution I found for it 👍 
Thanks @Gutyn

**Comment by Gutyn** [comment]
@coderabbitcrypto I just tried pulling master and updating the submodules and it builds, probably update all the things you can and use the standard NDK. Let me know if you have any ideas and I can guide you.

**Comment by ustoz** [comment]
Similar error when i tried to build on mac. Changing  '-DANDROID_STL= gnustl_static' to '-DANDROID_STL=c++_static' helped for me.

**Comment by shivangigandhi** [comment]
This should be fixed now.  After updating from NDK 17 to 18, CMAKE was failing with “'-DANDROID_STL=gnustl_static'“ flag.

The new ndk did not support custom ANDROID_STL and so it is failing to compile.

Fixed as of 3.4.0 (reference jira issue 863)
