### ISSUE TITLE
breadwallet freezes on mobile data

### ISSUE THREAD

**Issue by niayh** [breadwallet/breadwallet-android#8]
Device: Galaxy S6
OS: Android 6.0.1
Causes: 
* recovering a wallet on mobile data after a fresh installation or
* using a on mobile data wallet recovered while using wifi from a fresh installation
Symptoms:
* no sync status
* cannot use sidebar (app will crash)
Notes:
Swiping left and right at the main page seems fine. The wallet address is displayed along with options to send money. Scanning a QR code causes a crash too. Trying to use the menu to view transactions or settings causes the app to stop responding.

Logcat:
http://pastebin.com/wCqbvWEv

**Comment by Gutyn** [comment]
Thanks for the feedback @niayh, and sorry for the late response, this bug has been fixed and the new version will pe pushed to beta today.
