### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by KaushikTechcronus** [breadwallet/breadwallet-android#80]
Hello,

I'm using wallet for transferring lite coin.
But I'm facing issue jni.h not found in all places.
As per your previus answer I downgraded ndk to r15c.
After that lot of error occurs. BRBase58.h not found and lot more classes not found which are available.

Information:Gradle tasks [:app:assembleDemoDebug]
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
D:\AndroidStudioProjects\loafwallet-android-rebranding\app\src\main\jni\transition\JNIBase58.c
Error:(7, 10) fatal error: 'BRBase58.h' file not found
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
D:\AndroidStudioProjects\loafwallet-android-rebranding\app\src\main\jni\transition\JNIBIP32Sequence.c
Error:(6, 10) fatal error: 'BRKey.h' file not found
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
D:\AndroidStudioProjects\loafwallet-android-rebranding\app\src\main\jni\transition\JNIKey.c
Error:(6, 10) fatal error: 'BRInt.h' file not found
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
D:\AndroidStudioProjects\loafwallet-android-rebranding\app\src\main\jni\transition\wallet.h
Error:(25, 10) fatal error: 'BRInt.h' file not found
Error:(25, 10) fatal error: 'BRInt.h' file not found
Warning:warning: 'BITCOIN_TESTNET' macro redefined [-Wmacro-redefined]
D:\AndroidStudioProjects\loafwallet-android-rebranding\app\src\main\jni\transition\PeerManager.h
Error:(26, 10) fatal error: 'BRInt.h' file not found
Error:Execution failed for task ':app:compileCoreArm64-v8aDebugDemoSharedLibraryCoreArm64-v8aDebugDemoSharedLibraryMainC'.
> Multiple build operations failed.
      C compiler failed while compiling JNIBase58.c.
      C compiler failed while compiling JNIBIP32Sequence.c.
      C compiler failed while compiling core.c.
      C compiler failed while compiling JNIKey.c.
      C compiler failed while compiling wallet.c.
      C compiler failed while compiling PeerManager.c.
  See the complete log at: file:///D:/AndroidStudioProjects/loafwallet-android-rebranding/app/build/tmp/compileCoreArm64-v8aDebugDemoSharedLibraryCoreArm64-v8aDebugDemoSharedLibraryMainC/output.txt
Information:BUILD FAILED
Information:Total time: 12.515 secs
Information:7 errors
Information:6 warnings
Information:See complete output in console

Please help me with this.

**Comment by DrewCarlson** [comment]
This error is not relevant and not occur anymore.  Please report any further issues.
