### ISSUE TITLE
F-Driod

### ISSUE THREAD

**Issue by trymeouteh** [breadwallet/breadwallet-android#81]
Please add this app on F-Driod so Andriod users who do not have Google Play Store on their phones can get the BRD wallet.

**Comment by shivangigandhi** [comment]
Hi, 

Thanks for the suggestion.  Unfortunately, we are not eligible because we use Crashlytics and Firebase.

https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by trymeouteh** [comment]
Please remove the Crashlytics and Firebase.
