### ISSUE TITLE
Doesn't sync the ethereum wallet on Android 9.0

### ISSUE THREAD

**Issue by AlexDCryptoC** [breadwallet/breadwallet-android#83]
After i updated my device to Android 9.0, the ethereum wallet doesn't sync anymore and i can't see any value even ERC20 tokens.

**Comment by praxais** [comment]
It seems to be fixed in the latest code push.. but can anyone tell how was it fixed ?

**Comment by shivangigandhi** [comment]
The user agent string was corrected in 3.7.0 (reference jira issue #1073).  @praxais, thank you for posting your solution!
