### ISSUE TITLE
BRD can not be authenticated due to a bug in your version of Android. [Please tap here for more information.]

### ISSUE THREAD

**Issue by Transisto** [breadwallet/breadwallet-android#84]
"tap here for more information" links to "article not found"

https://github.com/breadwallet/breadwallet-android/blob/368c3a638c9a5275a2221b80fbcc976164b7ceaa/app/src/main/res/values/strings.xml#L200

**Comment by shivangigandhi** [comment]
The dialog should no longer appear as of 3.8.1 (reference jira issue #1207)
