### ISSUE TITLE
Missing feature: insufficient funds when device is locked

### ISSUE THREAD

**Issue by jmacwhyte** [breadwallet/breadwallet-android#9]
How to reproduce: On one device, "request an amount" for more than what is in the second device's wallet. Start breadwallet on the second device, but do not unlock the wallet (i.e. the lock icon still shows in the top right). When you scan the QR with the second device, you will get the message "insufficient funds for bitcoin network fee" with an "ok" button.

Instead, the user should be asked to enter their passcode to complete the payment (which also unlocks the wallet), and should then be told their balance is insufficient and asked if they would like to change the send amount.

See iOS implementation for reference.

**Comment by Gutyn** [comment]
Looking at my code it sounds like the wallet is unlocked but the icon is showing after it went back from the background, I will check.

**Comment by jmacwhyte** [comment]
If the wallet is unlocked, scanning a QR that asks for too much money gives you the option to change the amount. Whether the wallet is locked or not, it should always give that option (after asking for passcode if needed).
