### ISSUE TITLE
Gradle sync issue

### ISSUE THREAD

**Issue by ektitova** [breadwallet/breadwallet-android#91]
Hi everyone !
Faced some error during Gradle syncing :
* What went wrong:
Some problems were found with the configuration of task ':app:generateBrdDebugProto'.
> Directory '... \app\build\extracted-include-protos\main' specified for property '$3' does not exist.
> Directory '.... \app\build\extracted-include-protos\brd' specified for property '$6' does not exist.
> Directory '... \app\build\extracted-include-protos\debug' specified for property '$9' does not exist.

As I understood issue is reproduced cause of updated Gradle 5.0

**Comment by nashsclay** [comment]
When you run and clone the project, it will give you a choice to update the gradle for the project. DO NOT UPGRADE.

**Comment by shivangigandhi** [comment]
Thanks for posting the resolution, @nashsclay !
