### ISSUE TITLE
[Suggestion] Remove Non-free Services

### ISSUE THREAD

**Issue by ghbjklhv** [breadwallet/breadwallet-android#96]
**Issue**: Make free-only version without non-free services like [Crashlytics](https://www.wikipedia.org/wiki/Crashlytics) and [Firebase](https://www.wikipedia.org/wiki/Firebase).
**Objective**: Make [F-Droid](https://www.wikipedia.org/wiki/F-Droid) compliant-version for free software OSes like [Replicant](https://www.wikipedia.org/wiki/Replicant_(operating_system)). 
**Related Links**:
https://f-droid.org/en/docs/Inclusion_Policy/

https://gitlab.com/fdroid/rfp/issues/604

__________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/76321708-suggestion-remove-non-free-services)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=76321708)](https://www.bountysource.com/issues/76321708-suggestion-remove-non-free-services)

**Comment by shivangigandhi** [comment]
@ghbjklhv, Thank you for the suggestion.  At this time we don't have plans to make such an offering as it does not align with our current plans.

**Comment by trymeouteh** [comment]
Please remove the Crashlytics and Firebase.
