### ISSUE TITLE
when will you submit your newest of 3.9.11, I really hope do this soon, very thinks

### ISSUE THREAD

**Issue by bingbingbing63** [breadwallet/breadwallet-android#98]
I found the verison of 3.9.0 of now went crash of input system passwd activity, and i can't solve it by every ways. However ,i search of Google play, then i found there was a new version of breadwallet of 3.9.11 ,and it went very well on my android phone which brand is MeiZu, the android version is 7.1.1, 
I thind  you had already  sovled the problem very well，so if you submit you code then i will pull down at once, and i am very glad to do this. Thanks very well

**Comment by shivangigandhi** [comment]
We will update github ASAP.  Thanks!

**Comment by bingbingbing63** [comment]
i had found the problem and make the project success, and let it run ok,thinks a lot

**Comment by shivangigandhi** [comment]
Updated to the lasted.  Sorry for the delay!
