### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by ghost** [breadwallet/breadwallet-android#99]
```

> Unable to resolve dependency for ':app@brdDebug/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> -- | --
> Unable to resolve dependency for ':app@brdDebugAndroidTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdDebugUnitTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdRelease/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdReleaseUnitTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdTestnetDebug/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdTestnetDebugAndroidTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdTestnetDebugUnitTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdTestnetRelease/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> Unable to resolve dependency for ':app@brdTestnetReleaseUnitTest/compileClasspath': Could not resolve project :CoreLibrary. Show Details Affected Modules: app |  
> 
> 

```

**Comment by VaivalGithub** [comment]
@KaisDev  we are also facing the issue on our end as well.

ERROR: Unable to resolve dependency for ':app@brdDebug/compileClasspath': Could not resolve project :CoreLibrary.

Do you have any progress on this ?

**Comment by KaisDev** [comment]
> 
> 
> @KaisDev we are also facing the issue on our end as well.
> 
> ERROR: Unable to resolve dependency for ':app@brdDebug/compileClasspath': Could not resolve project :CoreLibrary.
> 
> Do you have any progress on this ?

I am trying to solve this problem and I think there's a new version coming up soon

**Comment by ramalik** [comment]
> > @KaisDev we are also facing the issue on our end as well.
> > ERROR: Unable to resolve dependency for ':app@brdDebug/compileClasspath': Could not resolve project :CoreLibrary.
> > Do you have any progress on this ?
> 
> I am trying to solve this problem and I think there's a new version coming up soon

@KaisDev  i am facing same issue.
Have you found out any solution?
As i tried many things to fix the issue but issue is still there.

**Comment by DrewCarlson** [comment]
Have you followed the setup instructions?  Specifically the submodule checkout steps.

Does the project sync/build after running `git submodule update --init --recursive`?

**Comment by mutablestudio** [comment]
I solved this by removing the core dir in project root and re-running the git submodule commands, then rebuild
